import {useEffect,useMemo,useState} from 'react'
import {ArrowLeft,Box,Check,ChevronDown,ChevronRight,FileText,Library,MoreHorizontal,Package,Plus,Save,Send,Share2,Trash2,X} from 'lucide-react'
import {supabase} from '../lib/supabase'

type Basis='flat'|'per_actual_kg'|'per_chargeable_kg'|'per_lb'|'per_cbm'|'per_piece'|'per_pallet'|'per_container'
type Cargo={id:string;quantity:number;packaging_type:string|null;commodity:string|null;weight_value:number|null;weight_unit:string|null;length_value:number|null;width_value:number|null;height_value:number|null;dimension_unit:string|null}
type Charge={id:string;description:string;basis:Basis;quantity:number;rate:number;sellRate:number;markup:number;minimum:number;cost:number;sell:number;autoQuantity:boolean;source?:string}
type QuoteRow={id:string;quote_number:string;customer_name:string|null;status:string;quote_data:any;quote_request_id:string|null}
type LibraryCharge={id:string;name:string;type:string;rate:number;qty:number;minimum:number}
type Preset={id:string;name:string;charges:any[]}
type QuoteTab='preview'|'charges'|'cargo'|'terms'|'shipment'
type Sheet='shipment'|'template'|'cargo'|null

const labels:Record<Basis,string>={flat:'Flat',per_actual_kg:'Actual kg',per_chargeable_kg:'Chargeable kg',per_lb:'Lb',per_cbm:'CBM',per_piece:'Piece',per_pallet:'Pallet',per_container:'Container'}
const tabs:{id:QuoteTab;label:string}[]=[{id:'preview',label:'Preview'},{id:'charges',label:'Charges'},{id:'cargo',label:'Cargo'},{id:'terms',label:'Terms'},{id:'shipment',label:'Shipment'}]
const n=(v:any)=>Number(v)||0
const clean=(v:number,places=4)=>Number.isFinite(v)?Number(v.toFixed(places)):0
const inputValue=(v:number,places=4)=>v===0?'':String(clean(v,places))
const t=(v:any,f='')=>v==null||v===''?f:String(v)
const money=(v:number,c='USD')=>{try{return new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(v)}catch{return `$${v.toFixed(2)}`}}
const basis=(v:string):Basis=>({per_kg:'per_actual_kg',kg:'per_actual_kg',lb:'per_lb',cbm:'per_cbm',pallet:'per_pallet',container:'per_container'} as any)[v]||v as Basis||'flat'
const blank=():Charge=>({id:crypto.randomUUID(),description:'New charge',basis:'flat',quantity:1,rate:0,sellRate:0,markup:0,minimum:0,cost:0,sell:0,autoQuantity:false})
const blankCargo=():Cargo=>({id:crypto.randomUUID(),quantity:1,packaging_type:'pallet',commodity:'Cargo',weight_value:0,weight_unit:'kg',length_value:0,width_value:0,height_value:0,dimension_unit:'cm'})

function cargoMetrics(cargo:Cargo[]){let actualKg=0,cbm=0,pieces=0,pallets=0,containers=0;for(const c of cargo){const q=n(c.quantity),w=n(c.weight_value),f=t(c.dimension_unit,'cm').toLowerCase()==='in'?2.54:1;pieces+=q;actualKg+=(t(c.weight_unit,'kg').toLowerCase()==='lb'?w*.453592:w)*q;cbm+=n(c.length_value)*f*n(c.width_value)*f*n(c.height_value)*f/1e6*q;const p=t(c.packaging_type).toLowerCase();if(p.includes('pallet'))pallets+=q;if(p.includes('container'))containers+=q}return{actualKg,chargeableKg:Math.max(actualKg,cbm*167),lb:actualKg*2.20462,cbm,pieces,pallets,containers}}
const qty=(b:Basis,m:ReturnType<typeof cargoMetrics>)=>({flat:1,per_actual_kg:m.actualKg,per_chargeable_kg:m.chargeableKg,per_lb:m.lb,per_cbm:m.cbm,per_piece:m.pieces,per_pallet:m.pallets,per_container:m.containers}[b]||1)
const calc=(c:Charge,m:ReturnType<typeof cargoMetrics>)=>{const quantity=clean(c.autoQuantity?qty(c.basis,m):n(c.quantity)),cost=clean(Math.max(quantity*n(c.rate),n(c.minimum)),2),sell=clean(Math.max(quantity*n(c.sellRate),0),2),markup=n(c.rate)?clean((n(c.sellRate)/n(c.rate)-1)*100,2):clean(n(c.markup),2);return{...c,quantity,cost,sell,markup}}
const normalizeCargo=(rows:any[]):Cargo[]=>(rows||[]).map(c=>({id:c.id||crypto.randomUUID(),quantity:n(c.quantity??c.qty)||1,packaging_type:t(c.packaging_type??c.desc,'piece'),commodity:t(c.commodity??c.desc,'Cargo'),weight_value:n(c.weight_value??c.weight),weight_unit:t(c.weight_unit??c.wUnit,'kg'),length_value:n(c.length_value??c.l),width_value:n(c.width_value??c.w),height_value:n(c.height_value??c.h),dimension_unit:t(c.dimension_unit??c.dUnit,'cm')}))
const normalizeCharges=(rows:any[],m:ReturnType<typeof cargoMetrics>):Charge[]=>(rows||[]).map(c=>{const b=basis(t(c.basis??c.type,'flat')),quantity=n(c.quantity??c.qty)||qty(b,m),rate=n(c.rate)||(b==='flat'?n(c.amount??c.cost):0),cost=n(c.cost??c.amount)||Math.max(quantity*rate,n(c.minimum)),sell=n(c.sell??c.amount)||cost,sellRate=n(c.sellRate??c.sell_rate)||(quantity?sell/quantity:sell)||rate;return calc({id:c.id||crypto.randomUUID(),description:t(c.description??c.name,'Charge'),basis:b,quantity,rate,sellRate,markup:0,minimum:n(c.minimum),cost,sell,autoQuantity:c.autoQuantity??b!=='flat',source:c.source},m)})

export function MobileQuoteWorkspace({quoteId,onClose}:{quoteId:string;onClose:()=>void}){
 const[tab,setTab]=useState<QuoteTab>('preview'),[quote,setQuote]=useState<QuoteRow|null>(null),[cargo,setCargo]=useState<Cargo[]>([]),[charges,setCharges]=useState<Charge[]>([]),[library,setLibrary]=useState<LibraryCharge[]>([]),[presets,setPresets]=useState<Preset[]>([]),[presetName,setPresetName]=useState(''),[libraryOpen,setLibraryOpen]=useState(false),[menu,setMenu]=useState(false),[shipmentOpen,setShipmentOpen]=useState(false),[sheet,setSheet]=useState<Sheet>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const[customer,setCustomer]=useState(''),[email,setEmail]=useState(''),[reference,setReference]=useState(''),[commodity,setCommodity]=useState(''),[mode,setMode]=useState(''),[service,setService]=useState(''),[incoterm,setIncoterm]=useState(''),[origin,setOrigin]=useState(''),[destination,setDestination]=useState(''),[currency,setCurrency]=useState('USD'),[carrier,setCarrier]=useState(''),[transit,setTransit]=useState(''),[validUntil,setValidUntil]=useState(''),[notes,setNotes]=useState(''),[terms,setTerms]=useState('')
 const metrics=useMemo(()=>cargoMetrics(cargo),[cargo])
 const totals=useMemo(()=>{const cost=charges.reduce((s,c)=>s+c.cost,0),sell=charges.reduce((s,c)=>s+c.sell,0),profit=sell-cost;return{cost,sell,profit,margin:sell?profit/sell*100:0}},[charges])

 useEffect(()=>{(async()=>{setLoading(true);const[{data:q,error},{data:lib},{data:pre}]=await Promise.all([supabase.from('quotes').select('*').eq('id',quoteId).single(),supabase.from('charge_library').select('id,name,type,rate,qty,minimum').order('name'),supabase.from('charge_presets').select('id,name,charges').order('name')]);if(error||!q){setMessage(error?.message||'Quote not found');setLoading(false);return}const row=q as QuoteRow,d=row.quote_data||{};let cg=normalizeCargo(d.cargo||[]);if(row.quote_request_id){const{data}=await supabase.from('quote_request_cargo').select('*').eq('quote_request_id',row.quote_request_id).order('line_number');if(data?.length)cg=normalizeCargo(data)}const m=cargoMetrics(cg);setQuote(row);setCargo(cg);setLibrary((lib||[]) as LibraryCharge[]);setPresets((pre||[]) as Preset[]);setPresetName(t(d.preset));setCharges(normalizeCharges(d.charges||[],m));setCustomer(t(row.customer_name,'Customer'));setEmail(t(d.customerEmail));setReference(t(d.customerReference));setCommodity(t(d.commodity,cg.map(x=>x.commodity).filter(Boolean).join(', ')));setMode(t(d.mode));setService(t(d.serviceType));setIncoterm(t(d.incoterm));const r=t(d.route).split('→');setOrigin(t(d.origin,r[0]?.trim()));setDestination(t(d.destination,r[1]?.trim()));setCurrency(t(d.currency,'USD'));setCarrier(t(d.carrier,d.vendor?.name));setTransit(t(d.transit));setValidUntil(t(d.validUntil));setNotes(t(d.customerNotes));setTerms(t(d.terms));setLoading(false)})()},[quoteId])
 useEffect(()=>setCharges(rows=>rows.map(c=>calc(c,metrics))),[metrics.actualKg,metrics.cbm,metrics.pieces,metrics.pallets,metrics.containers])
 const patch=(id:string,p:Partial<Charge>)=>setCharges(rows=>rows.map(c=>c.id===id?calc({...c,...p},metrics):c))
 const patchCargo=(id:string,p:Partial<Cargo>)=>setCargo(rows=>rows.map(c=>c.id===id?{...c,...p}:c))
 const addLibrary=(item:LibraryCharge)=>{const b=basis(item.type),rate=n(item.rate);setCharges(v=>[...v,calc({id:crypto.randomUUID(),description:item.name,basis:b,quantity:qty(b,metrics),rate,sellRate:rate,markup:0,minimum:n(item.minimum),cost:0,sell:0,autoQuantity:b!=='flat',source:'library'},metrics)]);setLibraryOpen(false)}
 const applyPreset=(preset:Preset)=>{const rows=(preset.charges||[]).map(x=>{const b=basis(t(x.type??x.basis,'flat')),quantity=qty(b,metrics),rate=n(x.rate);return calc({id:crypto.randomUUID(),description:t(x.name,'Charge'),basis:b,quantity,rate,sellRate:rate,markup:0,minimum:n(x.minimum),cost:0,sell:0,autoQuantity:b!=='flat',source:'template'},metrics)});setCharges(rows);setPresetName(preset.name);setSheet(null);setTab('charges')}
 const save=async(status='draft')=>{if(!quote)return;setSaving(true);const data={...(quote.quote_data||{}),customerEmail:email,customerReference:reference,commodity,mode,serviceType:service,incoterm,origin,destination,route:`${origin} → ${destination}`,currency,carrier,transit,validUntil,customerNotes:notes,terms,preset:presetName,cargo,metrics,charges,totals};const{data:updated,error}=await supabase.from('quotes').update({customer_name:customer,status,quote_data:data}).eq('id',quote.id).select('*').single();setSaving(false);if(error){setMessage(error.message);return}setQuote(updated as QuoteRow);setMessage(status==='sent'?'Quote marked sent.':'Quote saved.')}
 const createPdf=()=>{setMenu(false);setTab('preview');window.setTimeout(()=>window.print(),350)}
 const shareQuote=async()=>{const text=`${quote?.quote_number||'Freight quotation'}\n${customer}\n${origin} → ${destination}\nTotal: ${money(totals.sell,currency)}`;if(navigator.share){await navigator.share({title:quote?.quote_number||'Freight quotation',text})}else{await navigator.clipboard.writeText(text);setMessage('Quote summary copied.')}}
 if(loading)return <div className="mobile-quote-loading">Loading quote…</div>

 return <div className="mobile-quote-app">
  <header className="mobile-quote-head"><button onClick={onClose}><ArrowLeft/></button><div><small>QUOTE</small><h1>{quote?.quote_number}</h1><p>{customer}</p></div><button onClick={()=>setMenu(!menu)}><MoreHorizontal/></button>{menu&&<div className="mobile-quote-menu"><button onClick={createPdf}><FileText/>Create PDF</button><button onClick={shareQuote}><Share2/>Share quote</button><button onClick={()=>location.href=`mailto:${email}`}><Send/>Email quote</button><button onClick={()=>setMenu(false)}>Close menu</button></div>}</header>

  <button className={`mobile-shipment-canvas ${shipmentOpen?'open':''}`} onClick={()=>setShipmentOpen(v=>!v)}><div className="shipment-canvas-top"><span className="shipment-mode"><Package size={16}/>{mode||'Freight'}</span><span>{service||'Service pending'}</span><ChevronDown size={17}/></div><strong>{origin||'Origin'} <i>→</i> {destination||'Destination'}</strong><div className="shipment-canvas-metrics"><span><b>{metrics.pieces}</b> pieces</span><span><b>{metrics.chargeableKg.toFixed(1)}</b> chargeable kg</span><span><b>{metrics.cbm.toFixed(3)}</b> CBM</span></div>{shipmentOpen&&<div className="shipment-canvas-actions"><span onClick={e=>{e.stopPropagation();setSheet('shipment')}}><b>Shipment</b><small>Mode, route and service</small><ChevronRight/></span><span onClick={e=>{e.stopPropagation();setSheet('template')}}><b>Template</b><small>{presetName||'Choose pricing template'}</small><ChevronRight/></span><span onClick={e=>{e.stopPropagation();setSheet('cargo')}}><b>Cargo</b><small>{cargo.length} package line{cargo.length===1?'':'s'}</small><ChevronRight/></span></div>}</button>

  <nav className="mobile-quote-tabs" aria-label="Quote sections">{tabs.map(x=><button type="button" className={tab===x.id?'active':''} onClick={()=>setTab(x.id)} key={x.id}>{x.label}</button>)}</nav>
  <main className="mobile-quote-body">
   {tab==='preview'&&<section className="mobile-section preview-section"><div className="mobile-preview"><header><div><small>MIP CARGO EXPRESS</small><h2>Freight quotation</h2></div><span>{quote?.quote_number}</span></header><section className="mobile-preview-customer"><small>PREPARED FOR</small><h3>{customer}</h3><p>{email}</p></section><section className="mobile-preview-route"><small>SHIPMENT</small><h3>{origin||'Origin'} → {destination||'Destination'}</h3><p>{[mode,service,incoterm].filter(Boolean).join(' · ')}</p><div><span><small>Pieces</small><b>{metrics.pieces}</b></span><span><small>Chargeable</small><b>{metrics.chargeableKg.toFixed(1)} kg</b></span><span><small>Volume</small><b>{metrics.cbm.toFixed(3)} CBM</b></span></div></section><section className="mobile-preview-lines">{charges.map(c=><span key={c.id}>{c.description}<b>{money(c.sell,currency)}</b></span>)}</section><footer><span>Total quotation</span><b>{money(totals.sell,currency)}</b></footer>{notes&&<p className="mobile-preview-notes">{notes}</p>}{terms&&<small className="mobile-preview-terms">{terms}</small>}</div></section>}
   {tab==='charges'&&<section className="mobile-section"><div className="mobile-section-title"><div><small>PRICING</small><h2>Charges</h2><p>{charges.length} items · edit customer pricing</p></div><div><button onClick={()=>setLibraryOpen(true)}><Library/>Library</button><button onClick={()=>setCharges(v=>[...v,blank()])}><Plus/>Manual</button></div></div>{charges.map(c=><article className="mobile-charge expanded" key={c.id}><div className="mobile-charge-title"><div><input value={c.description} onChange={e=>patch(c.id,{description:e.target.value})}/><small>{labels[c.basis]} · {money(c.sell,currency)}</small></div><button onClick={()=>setCharges(v=>v.filter(x=>x.id!==c.id))}><Trash2/></button></div><div className="mobile-charge-grid"><label>Basis<select value={c.basis} onChange={e=>patch(c.id,{basis:e.target.value as Basis,autoQuantity:e.target.value!=='flat'})}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Quantity<input type="number" step="0.0001" inputMode="decimal" value={inputValue(c.quantity)} onChange={e=>patch(c.id,{quantity:n(e.target.value),autoQuantity:false})}/></label><label>Vendor rate<input type="number" step="0.01" inputMode="decimal" value={inputValue(c.rate,2)} onChange={e=>{const rate=n(e.target.value);patch(c.id,{rate,sellRate:c.sellRate||rate})}}/></label><label>Markup %<input type="number" step="0.1" inputMode="decimal" value={inputValue(c.markup,2)} onChange={e=>{const markup=n(e.target.value);patch(c.id,{markup,sellRate:clean(c.rate*(1+markup/100),4)})}}/></label><label>Customer rate<input type="number" step="0.01" inputMode="decimal" value={inputValue(c.sellRate,4)} onChange={e=>patch(c.id,{sellRate:n(e.target.value)})}/></label><label>Minimum<input type="number" step="0.01" inputMode="decimal" value={inputValue(c.minimum,2)} onChange={e=>patch(c.id,{minimum:n(e.target.value)})}/></label></div><div className="mobile-charge-total"><span>Vendor cost<b>{money(c.cost,currency)}</b></span><span>Customer sell<b>{money(c.sell,currency)}</b></span></div></article>)}</section>}
   {tab==='cargo'&&<section className="mobile-section"><div className="mobile-section-title"><div><small>CARGO</small><h2>Cargo summary</h2><p>Weights and dimensions used for pricing</p></div><div><button onClick={()=>setSheet('cargo')}>Edit</button></div></div><div className="mobile-metrics"><span>Actual<b>{metrics.actualKg.toFixed(1)} kg</b></span><span>Chargeable<b>{metrics.chargeableKg.toFixed(1)} kg</b></span><span>Volume<b>{metrics.cbm.toFixed(3)}</b></span><span>Pieces<b>{metrics.pieces}</b></span></div><div className="mobile-cargo-list">{cargo.length?cargo.map(c=><button className="mobile-cargo" key={c.id} onClick={()=>setSheet('cargo')}><Box/><div><b>{c.quantity} {c.packaging_type}</b><span>{c.commodity||'Cargo'}</span><small>{c.weight_value||0} {c.weight_unit||'kg'} · {c.length_value||0} × {c.width_value||0} × {c.height_value||0} {c.dimension_unit||'cm'}</small></div><ChevronRight/></button>):<p className="mobile-empty-copy">No cargo lines are attached to this quote.</p>}</div></section>}
   {tab==='terms'&&<section className="mobile-section"><div className="mobile-section-title"><div><small>CONDITIONS</small><h2>Terms</h2></div></div><div className="mobile-form"><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD</option><option>EUR</option><option>GBP</option></select></label><label>Carrier / Airline<input value={carrier} onChange={e=>setCarrier(e.target.value)}/></label><label>Transit<input value={transit} onChange={e=>setTransit(e.target.value)}/></label><label>Valid until<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><label className="full">Customer notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="full">Terms<textarea value={terms} onChange={e=>setTerms(e.target.value)}/></label></div></section>}
   {tab==='shipment'&&<section className="mobile-section"><div className="mobile-section-title"><div><small>SHIPMENT</small><h2>Shipment details</h2><p>Customer, routing, and service information</p></div></div><div className="mobile-form"><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)}/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Reference<input value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Commodity<input value={commodity} onChange={e=>setCommodity(e.target.value)}/></label><label>Mode<input value={mode} onChange={e=>setMode(e.target.value)}/></label><label>Service<input value={service} onChange={e=>setService(e.target.value)}/></label><label>Origin<input value={origin} onChange={e=>setOrigin(e.target.value)}/></label><label>Destination<input value={destination} onChange={e=>setDestination(e.target.value)}/></label><label>Incoterm<input value={incoterm} onChange={e=>setIncoterm(e.target.value)}/></label></div></section>}
   {message&&<p className="mobile-quote-message">{message}</p>}
  </main>

  <footer className="mobile-quote-footer"><div><span>Total sell</span><b>{money(totals.sell,currency)}</b><small>{money(totals.profit,currency)} profit · {totals.margin.toFixed(1)}%</small></div><button onClick={()=>save('draft')} disabled={saving}><Save/>Save</button><button className="primary" onClick={()=>save('sent')} disabled={saving}><Send/>Send</button></footer>

  {libraryOpen&&<div className="mobile-library"><section><header><div><small>CHARGE LIBRARY</small><h2>Add a charge</h2></div><button onClick={()=>setLibraryOpen(false)}><X/></button></header><div>{library.map(x=><button onClick={()=>addLibrary(x)} key={x.id}><span><b>{x.name}</b><small>{labels[basis(x.type)]}</small></span><Plus/></button>)}</div></section></div>}

  {sheet&&<div className="mobile-native-sheet" onClick={()=>setSheet(null)}><section onClick={e=>e.stopPropagation()}><header><div><small>{sheet==='template'?'PRICING':sheet==='cargo'?'CARGO':'SHIPMENT'}</small><h2>{sheet==='template'?'Choose template':sheet==='cargo'?'Edit cargo':'Shipment settings'}</h2></div><button onClick={()=>setSheet(null)}><X/></button></header>
   {sheet==='template'&&<div className="native-option-list">{presets.map(p=><button key={p.id} onClick={()=>applyPreset(p)}><span><b>{p.name}</b><small>{(p.charges||[]).length} charges</small></span>{presetName===p.name?<Check/>:<ChevronRight/>}</button>)}</div>}
   {sheet==='shipment'&&<div className="mobile-sheet-form"><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="air">Air</option><option value="ocean">Ocean</option><option value="ground">Ground</option><option value="courier">Courier</option></select></label><label>Service<input value={service} onChange={e=>setService(e.target.value)} placeholder="Door to Door"/></label><div className="split"><label>Origin<input value={origin} onChange={e=>setOrigin(e.target.value)} placeholder="MIA"/></label><label>Destination<input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="UIO"/></label></div><label>Incoterm<input value={incoterm} onChange={e=>setIncoterm(e.target.value)} placeholder="EXW"/></label><button className="sheet-done" onClick={()=>setSheet(null)}>Done</button></div>}
   {sheet==='cargo'&&<div className="mobile-cargo-editor">{cargo.map((c,index)=><article key={c.id}><header><b>Package {index+1}</b><button onClick={()=>setCargo(rows=>rows.filter(x=>x.id!==c.id))}><Trash2/></button></header><div className="split"><label>Quantity<input type="number" inputMode="numeric" value={inputValue(c.quantity)} onChange={e=>patchCargo(c.id,{quantity:n(e.target.value)})}/></label><label>Type<select value={c.packaging_type||'piece'} onChange={e=>patchCargo(c.id,{packaging_type:e.target.value})}><option>pallet</option><option>box</option><option>crate</option><option>piece</option><option>container</option></select></label></div><label>Commodity<input value={c.commodity||''} onChange={e=>patchCargo(c.id,{commodity:e.target.value})}/></label><div className="split"><label>Weight<input type="number" inputMode="decimal" value={inputValue(n(c.weight_value))} onChange={e=>patchCargo(c.id,{weight_value:n(e.target.value)})}/></label><label>Unit<select value={c.weight_unit||'kg'} onChange={e=>patchCargo(c.id,{weight_unit:e.target.value})}><option>kg</option><option>lb</option></select></label></div><div className="dimensions"><label>Length<input type="number" inputMode="decimal" value={inputValue(n(c.length_value))} onChange={e=>patchCargo(c.id,{length_value:n(e.target.value)})}/></label><label>Width<input type="number" inputMode="decimal" value={inputValue(n(c.width_value))} onChange={e=>patchCargo(c.id,{width_value:n(e.target.value)})}/></label><label>Height<input type="number" inputMode="decimal" value={inputValue(n(c.height_value))} onChange={e=>patchCargo(c.id,{height_value:n(e.target.value)})}/></label></div><label>Dimension unit<select value={c.dimension_unit||'cm'} onChange={e=>patchCargo(c.id,{dimension_unit:e.target.value})}><option>cm</option><option>in</option></select></label></article>)}<button className="add-package" onClick={()=>setCargo(rows=>[...rows,blankCargo()])}><Plus/>Add package</button><button className="sheet-done" onClick={()=>setSheet(null)}>Done</button></div>}
  </section></div>}
 </div>
}
