import {useEffect,useMemo,useState} from 'react'
import {ArrowLeft,Box,ChevronDown,Library,MoreHorizontal,Package,Plus,Save,Send,Trash2,X} from 'lucide-react'
import {supabase} from '../lib/supabase'

type Basis='flat'|'per_actual_kg'|'per_chargeable_kg'|'per_lb'|'per_cbm'|'per_piece'|'per_pallet'|'per_container'
type Cargo={id:string;quantity:number;packaging_type:string|null;commodity:string|null;weight_value:number|null;weight_unit:string|null;length_value:number|null;width_value:number|null;height_value:number|null;dimension_unit:string|null}
type Charge={id:string;description:string;basis:Basis;quantity:number;rate:number;sellRate:number;markup:number;minimum:number;cost:number;sell:number;autoQuantity:boolean;source?:string}
type QuoteRow={id:string;quote_number:string;customer_name:string|null;status:string;quote_data:any;quote_request_id:string|null}
type LibraryCharge={id:string;name:string;type:string;rate:number;qty:number;minimum:number}
type QuoteTab='preview'|'charges'|'cargo'|'terms'|'shipment'
const labels:Record<Basis,string>={flat:'Flat',per_actual_kg:'Actual kg',per_chargeable_kg:'Chargeable kg',per_lb:'Lb',per_cbm:'CBM',per_piece:'Piece',per_pallet:'Pallet',per_container:'Container'}
const tabs:{id:QuoteTab;label:string}[]=[{id:'preview',label:'Preview'},{id:'charges',label:'Charges'},{id:'cargo',label:'Cargo'},{id:'terms',label:'Terms'},{id:'shipment',label:'Shipment'}]
const n=(v:any)=>Number(v)||0
const t=(v:any,f='')=>v==null||v===''?f:String(v)
const money=(v:number,c='USD')=>{try{return new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(v)}catch{return `$${v.toFixed(2)}`}}
const basis=(v:string):Basis=>({per_kg:'per_actual_kg',kg:'per_actual_kg',lb:'per_lb',cbm:'per_cbm',pallet:'per_pallet',container:'per_container'} as any)[v]||v as Basis||'flat'
const blank=():Charge=>({id:crypto.randomUUID(),description:'New charge',basis:'flat',quantity:1,rate:0,sellRate:0,markup:0,minimum:0,cost:0,sell:0,autoQuantity:false})
function cargoMetrics(cargo:Cargo[]){let actualKg=0,cbm=0,pieces=0,pallets=0,containers=0;for(const c of cargo){const q=n(c.quantity),w=n(c.weight_value),f=t(c.dimension_unit,'cm').toLowerCase()==='in'?2.54:1;pieces+=q;actualKg+=(t(c.weight_unit,'kg').toLowerCase()==='lb'?w*.453592:w)*q;cbm+=n(c.length_value)*f*n(c.width_value)*f*n(c.height_value)*f/1e6*q;const p=t(c.packaging_type).toLowerCase();if(p.includes('pallet'))pallets+=q;if(p.includes('container'))containers+=q}return{actualKg,chargeableKg:Math.max(actualKg,cbm*167),lb:actualKg*2.20462,cbm,pieces,pallets,containers}}
const qty=(b:Basis,m:ReturnType<typeof cargoMetrics>)=>({flat:1,per_actual_kg:m.actualKg,per_chargeable_kg:m.chargeableKg,per_lb:m.lb,per_cbm:m.cbm,per_piece:m.pieces,per_pallet:m.pallets,per_container:m.containers}[b]||1)
const calc=(c:Charge,m:ReturnType<typeof cargoMetrics>)=>{const quantity=c.autoQuantity?qty(c.basis,m):n(c.quantity),cost=Math.max(quantity*n(c.rate),n(c.minimum)),sell=Math.max(quantity*n(c.sellRate),0);return{...c,quantity,cost,sell,markup:n(c.rate)?(n(c.sellRate)/n(c.rate)-1)*100:n(c.markup)}}
const normalizeCargo=(rows:any[]):Cargo[]=>(rows||[]).map(c=>({id:c.id||crypto.randomUUID(),quantity:n(c.quantity??c.qty)||1,packaging_type:t(c.packaging_type??c.desc,'piece'),commodity:t(c.commodity??c.desc,'Cargo'),weight_value:n(c.weight_value??c.weight),weight_unit:t(c.weight_unit??c.wUnit,'kg'),length_value:n(c.length_value??c.l),width_value:n(c.width_value??c.w),height_value:n(c.height_value??c.h),dimension_unit:t(c.dimension_unit??c.dUnit,'cm')}))
const normalizeCharges=(rows:any[],m:ReturnType<typeof cargoMetrics>):Charge[]=>(rows||[]).map(c=>{const b=basis(t(c.basis??c.type,'flat')),quantity=n(c.quantity??c.qty)||qty(b,m),rate=n(c.rate)||(b==='flat'?n(c.amount??c.cost):0),cost=n(c.cost??c.amount)||Math.max(quantity*rate,n(c.minimum)),sell=n(c.sell??c.amount)||cost,sellRate=n(c.sellRate??c.sell_rate)||(quantity?sell/quantity:sell)||rate;return calc({id:c.id||crypto.randomUUID(),description:t(c.description??c.name,'Charge'),basis:b,quantity,rate,sellRate,markup:0,minimum:n(c.minimum),cost,sell,autoQuantity:c.autoQuantity??b!=='flat',source:c.source},m)})

export function MobileQuoteWorkspace({quoteId,onClose}:{quoteId:string;onClose:()=>void}){
 const[tab,setTab]=useState<QuoteTab>('preview'),[quote,setQuote]=useState<QuoteRow|null>(null),[cargo,setCargo]=useState<Cargo[]>([]),[charges,setCharges]=useState<Charge[]>([]),[library,setLibrary]=useState<LibraryCharge[]>([]),[libraryOpen,setLibraryOpen]=useState(false),[menu,setMenu]=useState(false),[shipmentOpen,setShipmentOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const[customer,setCustomer]=useState(''),[email,setEmail]=useState(''),[reference,setReference]=useState(''),[commodity,setCommodity]=useState(''),[mode,setMode]=useState(''),[service,setService]=useState(''),[incoterm,setIncoterm]=useState(''),[origin,setOrigin]=useState(''),[destination,setDestination]=useState(''),[currency,setCurrency]=useState('USD'),[carrier,setCarrier]=useState(''),[transit,setTransit]=useState(''),[validUntil,setValidUntil]=useState(''),[notes,setNotes]=useState(''),[terms,setTerms]=useState('')
 const metrics=useMemo(()=>cargoMetrics(cargo),[cargo])
 const totals=useMemo(()=>{const cost=charges.reduce((s,c)=>s+c.cost,0),sell=charges.reduce((s,c)=>s+c.sell,0),profit=sell-cost;return{cost,sell,profit,margin:sell?profit/sell*100:0}},[charges])
 useEffect(()=>{(async()=>{setLoading(true);const[{data:q,error},{data:lib}]=await Promise.all([supabase.from('quotes').select('*').eq('id',quoteId).single(),supabase.from('charge_library').select('id,name,type,rate,qty,minimum').order('name')]);if(error||!q){setMessage(error?.message||'Quote not found');setLoading(false);return}const row=q as QuoteRow,d=row.quote_data||{};let cg=normalizeCargo(d.cargo||[]);if(row.quote_request_id){const{data}=await supabase.from('quote_request_cargo').select('*').eq('quote_request_id',row.quote_request_id).order('line_number');if(data?.length)cg=normalizeCargo(data)}const m=cargoMetrics(cg);setQuote(row);setCargo(cg);setLibrary((lib||[]) as LibraryCharge[]);setCharges(normalizeCharges(d.charges||[],m));setCustomer(t(row.customer_name,'Customer'));setEmail(t(d.customerEmail));setReference(t(d.customerReference));setCommodity(t(d.commodity,cg.map(x=>x.commodity).filter(Boolean).join(', ')));setMode(t(d.mode));setService(t(d.serviceType));setIncoterm(t(d.incoterm));const r=t(d.route).split('→');setOrigin(t(d.origin,r[0]?.trim()));setDestination(t(d.destination,r[1]?.trim()));setCurrency(t(d.currency,'USD'));setCarrier(t(d.carrier,d.vendor?.name));setTransit(t(d.transit));setValidUntil(t(d.validUntil));setNotes(t(d.customerNotes));setTerms(t(d.terms));setLoading(false)})()},[quoteId])
 useEffect(()=>setCharges(rows=>rows.map(c=>calc(c,metrics))),[metrics.actualKg,metrics.cbm,metrics.pieces,metrics.pallets,metrics.containers])
 const patch=(id:string,p:Partial<Charge>)=>setCharges(rows=>rows.map(c=>c.id===id?calc({...c,...p},metrics):c))
 const addLibrary=(item:LibraryCharge)=>{const b=basis(item.type),rate=n(item.rate);setCharges(v=>[...v,calc({id:crypto.randomUUID(),description:item.name,basis:b,quantity:qty(b,metrics),rate,sellRate:rate,markup:0,minimum:n(item.minimum),cost:0,sell:0,autoQuantity:b!=='flat',source:'library'},metrics)]);setLibraryOpen(false)}
 const save=async(status='draft')=>{if(!quote)return;setSaving(true);const data={...(quote.quote_data||{}),customerEmail:email,customerReference:reference,commodity,mode,serviceType:service,incoterm,origin,destination,route:`${origin} → ${destination}`,currency,carrier,transit,validUntil,customerNotes:notes,terms,cargo,metrics,charges,totals};const{data:updated,error}=await supabase.from('quotes').update({customer_name:customer,status,quote_data:data}).eq('id',quote.id).select('*').single();setSaving(false);if(error){setMessage(error.message);return}setQuote(updated as QuoteRow);setMessage(status==='sent'?'Quote marked sent.':'Quote saved.')}
 if(loading)return <div className="mobile-quote-loading">Loading quote…</div>
 return <div className="mobile-quote-app">
  <header className="mobile-quote-head"><button onClick={onClose}><ArrowLeft/></button><div><small>QUOTE</small><h1>{quote?.quote_number}</h1><p>{customer}</p></div><button onClick={()=>setMenu(!menu)}><MoreHorizontal/></button>{menu&&<div className="mobile-quote-menu"><button onClick={()=>window.print()}>Create PDF</button><button onClick={()=>location.href=`mailto:${email}`}>Email quote</button><button onClick={()=>setMenu(false)}>Close</button></div>}</header>
  <button className={`mobile-shipment-canvas ${shipmentOpen?'open':''}`} onClick={()=>setShipmentOpen(v=>!v)}><div className="shipment-canvas-top"><span className="shipment-mode"><Package size={16}/>{mode||'Freight'}</span><span>{service||'Service pending'}</span><ChevronDown size={17}/></div><strong>{origin||'Origin'} <i>→</i> {destination||'Destination'}</strong><div className="shipment-canvas-metrics"><span><b>{metrics.pieces}</b> pieces</span><span><b>{metrics.chargeableKg.toFixed(1)}</b> chargeable kg</span><span><b>{metrics.cbm.toFixed(3)}</b> CBM</span></div>{shipmentOpen&&<div className="shipment-canvas-expanded"><span>Customer<b>{customer}</b></span><span>Reference<b>{reference||'—'}</b></span><span>Incoterm<b>{incoterm||'—'}</b></span><span>Carrier<b>{carrier||'Not selected'}</b></span></div>}</button>
  <nav className="mobile-quote-tabs" aria-label="Quote sections">{tabs.map(x=><button type="button" className={tab===x.id?'active':''} onClick={()=>setTab(x.id)} key={x.id}>{x.label}</button>)}</nav>
  <main className="mobile-quote-body">
   {tab==='preview'&&<section className="mobile-section preview-section"><div className="mobile-preview"><header><div><small>MIP CARGO EXPRESS</small><h2>Freight quotation</h2></div><span>{quote?.quote_number}</span></header><section><h3>{customer}</h3><p>{origin||'Origin'} → {destination||'Destination'}</p><small>{[mode,service,incoterm].filter(Boolean).join(' · ')}</small></section><div>{charges.map(c=><span key={c.id}>{c.description}<b>{money(c.sell,currency)}</b></span>)}</div><footer><span>Total</span><b>{money(totals.sell,currency)}</b></footer></div></section>}
   {tab==='charges'&&<section className="mobile-section"><div className="mobile-section-title"><div><small>PRICING</small><h2>Charges</h2><p>{charges.length} items · tap a card to edit</p></div><div><button onClick={()=>setLibraryOpen(true)}><Library/>Library</button><button onClick={()=>setCharges(v=>[...v,blank()])}><Plus/>Manual</button></div></div>{charges.map(c=><article className="mobile-charge" key={c.id}><div className="mobile-charge-title"><div><input value={c.description} onChange={e=>patch(c.id,{description:e.target.value})}/><small>{labels[c.basis]} · {money(c.sell,currency)}</small></div><button onClick={()=>setCharges(v=>v.filter(x=>x.id!==c.id))}><Trash2/></button></div><div className="mobile-charge-grid"><label>Basis<select value={c.basis} onChange={e=>patch(c.id,{basis:e.target.value as Basis,autoQuantity:e.target.value!=='flat'})}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Quantity<input inputMode="decimal" value={c.quantity} onChange={e=>patch(c.id,{quantity:n(e.target.value),autoQuantity:false})}/></label><label>Vendor rate<input inputMode="decimal" value={c.rate||''} onChange={e=>patch(c.id,{rate:n(e.target.value),sellRate:c.sellRate||n(e.target.value)})}/></label><label>Markup %<input inputMode="decimal" value={c.markup||''} onChange={e=>{const markup=n(e.target.value);patch(c.id,{markup,sellRate:c.rate*(1+markup/100)})}}/></label><label>Customer rate<input inputMode="decimal" value={c.sellRate||''} onChange={e=>patch(c.id,{sellRate:n(e.target.value)})}/></label><label>Minimum<input inputMode="decimal" value={c.minimum||''} onChange={e=>patch(c.id,{minimum:n(e.target.value)})}/></label></div><div className="mobile-charge-total"><span>Cost <b>{money(c.cost,currency)}</b></span><span>Sell <b>{money(c.sell,currency)}</b></span></div></article>)}</section>}
   {tab==='cargo'&&<section className="mobile-section"><div className="mobile-section-title"><div><small>CARGO</small><h2>Cargo summary</h2><p>Weights and dimensions used for pricing</p></div></div><div className="mobile-metrics"><span>Actual<b>{metrics.actualKg.toFixed(1)} kg</b></span><span>Chargeable<b>{metrics.chargeableKg.toFixed(1)} kg</b></span><span>Volume<b>{metrics.cbm.toFixed(3)}</b></span><span>Pieces<b>{metrics.pieces}</b></span></div><div className="mobile-cargo-list">{cargo.length?cargo.map(c=><div className="mobile-cargo" key={c.id}><Box/><div><b>{c.quantity} {c.packaging_type}</b><span>{c.commodity||'Cargo'}</span><small>{c.weight_value||0} {c.weight_unit||'kg'} · {c.length_value||0} × {c.width_value||0} × {c.height_value||0} {c.dimension_unit||'cm'}</small></div></div>):<p className="mobile-empty-copy">No cargo lines are attached to this quote.</p>}</div></section>}
   {tab==='terms'&&<section className="mobile-section"><div className="mobile-section-title"><div><small>CONDITIONS</small><h2>Terms</h2></div></div><div className="mobile-form"><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD</option><option>EUR</option><option>GBP</option></select></label><label>Carrier / Airline<input value={carrier} onChange={e=>setCarrier(e.target.value)}/></label><label>Transit<input value={transit} onChange={e=>setTransit(e.target.value)}/></label><label>Valid until<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><label className="full">Customer notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="full">Terms<textarea value={terms} onChange={e=>setTerms(e.target.value)}/></label></div></section>}
   {tab==='shipment'&&<section className="mobile-section"><div className="mobile-section-title"><div><small>SHIPMENT</small><h2>Shipment details</h2><p>Customer, routing, and service information</p></div></div><div className="mobile-form"><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)}/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Reference<input value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Commodity<input value={commodity} onChange={e=>setCommodity(e.target.value)}/></label><label>Mode<input value={mode} onChange={e=>setMode(e.target.value)}/></label><label>Service<input value={service} onChange={e=>setService(e.target.value)}/></label><label>Origin<input value={origin} onChange={e=>setOrigin(e.target.value)}/></label><label>Destination<input value={destination} onChange={e=>setDestination(e.target.value)}/></label><label>Incoterm<input value={incoterm} onChange={e=>setIncoterm(e.target.value)}/></label></div></section>}
   {message&&<p className="mobile-quote-message">{message}</p>}
  </main>
  <footer className="mobile-quote-footer"><div><span>Total sell</span><b>{money(totals.sell,currency)}</b><small>{money(totals.profit,currency)} profit · {totals.margin.toFixed(1)}%</small></div><button onClick={()=>save('draft')} disabled={saving}><Save/>Save</button><button className="primary" onClick={()=>save('sent')} disabled={saving}><Send/>Send</button></footer>
  {libraryOpen&&<div className="mobile-library"><section><header><div><small>CHARGE LIBRARY</small><h2>Add a charge</h2></div><button onClick={()=>setLibraryOpen(false)}><X/></button></header><div>{library.map(x=><button onClick={()=>addLibrary(x)} key={x.id}><span><b>{x.name}</b><small>{labels[basis(x.type)]}</small></span><Plus/></button>)}</div></section></div>}
 </div>
}