import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Box, Check, Plane, Plus, Ship, Sparkles, Trash2, Truck, Warehouse } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Mode='air'|'ocean'|'ground'|'warehouse'|''
type Cargo={id:string;commodity:string;packagingType:string;qty:number;weight:number;weightUnit:'kg'|'lb';length:number;width:number;height:number;dimUnit:'cm'|'in';stackable:boolean;dangerousGoods:boolean}
type Form={company:string;contactName:string;email:string;phone:string;referenceNumber:string;mode:Mode;serviceType:string;originSearch:string;destinationSearch:string;cargoReadyDate:string;incoterm:string;targetRate:string;targetCurrency:string;targetUnit:string;specialInstructions:string;isBonded:boolean;isFTZ:boolean;priority:string}

const logo='https://raw.githubusercontent.com/N10ai/mip-tools/main/Untitled%20design%20-%201.png'
const steps=['Service','Contact','Route','Cargo','Extras','Review']
const services=[['pickup','Pickup'],['airport_transfer','Airport transfer'],['port_transfer','Port / CFS transfer'],['customs','Customs clearance'],['bonded','Bonded transport'],['ftz','FTZ handling'],['warehouse','Warehousing'],['packing','Packing / crating'],['insurance','Cargo insurance'],['delivery','Final delivery']]
const modes=[{id:'air',label:'Air freight',copy:'Fast airport and door service.',icon:Plane},{id:'ocean',label:'Ocean freight',copy:'FCL, LCL, port and door service.',icon:Ship},{id:'ground',label:'Ground freight',copy:'LTL, FTL and local transport.',icon:Truck},{id:'warehouse',label:'Warehousing',copy:'Storage, handling and distribution.',icon:Warehouse}] as const
const blankCargo=():Cargo=>({id:crypto.randomUUID(),commodity:'',packagingType:'pallet',qty:1,weight:0,weightUnit:'lb',length:48,width:40,height:48,dimUnit:'in',stackable:true,dangerousGoods:false})
const initial:Form={company:'',contactName:'',email:'',phone:'',referenceNumber:'',mode:'',serviceType:'',originSearch:'',destinationSearch:'',cargoReadyDate:'',incoterm:'',targetRate:'',targetCurrency:'USD',targetUnit:'total',specialInstructions:'',isBonded:false,isFTZ:false,priority:'best_value'}

export function PublicRequestPortal(){
 const[step,setStep]=useState(0),[form,setForm]=useState<Form>(initial),[cargo,setCargo]=useState<Cargo[]>([blankCargo()]),[extras,setExtras]=useState<string[]>([]),[aiText,setAiText]=useState(''),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState('')
 const patch=(p:Partial<Form>)=>setForm(v=>({...v,...p}))
 const totals=useMemo(()=>{let kg=0,cbm=0;for(const c of cargo){const f=c.dimUnit==='in'?2.54:1;kg+=(c.weightUnit==='lb'?c.weight*.453592:c.weight)*c.qty;cbm+=(c.length*f*c.width*f*c.height*f/1e6)*c.qty}return{kg,cbm,chargeable:Math.max(kg,cbm*167)}},[cargo])
 const toggle=(id:string)=>setExtras(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])
 const aiFill=()=>{const t=aiText.toLowerCase();if(t.includes('air')||t.includes('fly'))patch({mode:'air',specialInstructions:aiText});else if(t.includes('ocean')||t.includes('container'))patch({mode:'ocean',specialInstructions:aiText});else if(t.includes('truck'))patch({mode:'ground',specialInstructions:aiText});const m=t.match(/(\d+)\s*pallet/);if(m)setCargo([{...blankCargo(),qty:+m[1]}]);if(t.includes('pickup'))setExtras(x=>[...new Set([...x,'pickup'])]);if(t.includes('delivery'))setExtras(x=>[...new Set([...x,'delivery'])]);setStep(2)}
 const submit=async()=>{setSubmitting(true);setMessage('');const payload:any={...form,requestedServices:extras,targetRate:{amount:Number(form.targetRate)||null,currency:form.targetCurrency,unit:form.targetUnit},cargo:cargo.map(c=>({commodity:c.commodity,packagingType:c.packagingType,cargoType:c.dangerousGoods?'dg':'general',qty:c.qty,weight:{value:c.weight,unit:c.weightUnit},dimensions:{length:{value:c.length,unit:c.dimUnit},width:{value:c.width,unit:c.dimUnit},height:{value:c.height,unit:c.dimUnit}},stackable:c.stackable})),totals:{weight:{kg:{value:+totals.kg.toFixed(2),unit:'kg'}},volume:{cbm:{value:+totals.cbm.toFixed(3),unit:'m3'}},chargeableWeight:{kg:{value:+totals.chargeable.toFixed(2),unit:'kg'}}},includeInland:extras.some(x=>['pickup','delivery','airport_transfer','port_transfer'].includes(x))};const {data,error}=await supabase.functions.invoke('submit-quote-request',{body:payload});setSubmitting(false);if(error){setMessage(error.message);return}setMessage(`SUCCESS:${data.requestNumber}`)}
 if(message.startsWith('SUCCESS:'))return <div className="public-portal"><header className="portal-header"><img src={logo}/><div><b>MIP Cargo Express</b><span>Freight solutions made simple</span></div></header><main className="portal-success"><div><Check/></div><p>REQUEST RECEIVED</p><h1>Thank you.</h1><h2>Your reference is {message.split(':')[1]}</h2><span>Our pricing team will contact you shortly.</span><button onClick={()=>{setForm(initial);setCargo([blankCargo()]);setExtras([]);setStep(0);setMessage('')}}>Submit another request</button></main></div>
 return <div className="public-portal"><header className="portal-header"><img src={logo}/><div><b>MIP Cargo Express</b><span>Freight solutions made simple</span></div><a href="#/">Internal portal</a></header><div className="portal-progress"><div style={{width:`${step/(steps.length-1)*100}%`}}/></div><main className="portal-shell"><aside>{steps.map((s,i)=><div className={i===step?'active':i<step?'done':''} key={s}><i>{i<step?<Check size={13}/>:i+1}</i><span>{s}</span></div>)}</aside><section className="portal-stage">
 {step===0&&<><p className="portal-kicker">REQUEST A FREIGHT QUOTE</p><h1>What do you need to move?</h1><p className="portal-copy">Choose the main service. You can add pickup, customs, delivery, warehousing, and other services later.</p><div className="mode-grid">{modes.map(({id,label,copy,icon:Icon})=><button className={form.mode===id?'selected':''} onClick={()=>patch({mode:id})} key={id}><Icon/><b>{label}</b><span>{copy}</span>{form.mode===id&&<i><Check size={14}/></i>}</button>)}</div><div className="ai-box"><div><Sparkles/><b>Describe it with AI</b><span>Paste an email or shipment description.</span></div><textarea value={aiText} onChange={e=>setAiText(e.target.value)} placeholder="Pick up 3 pallets in Doral and fly them from MIA to Quito..."/><button disabled={!aiText.trim()} onClick={aiFill}><Sparkles size={16}/> Fill automatically</button></div></>}
 {step===1&&<><p className="portal-kicker">CONTACT</p><h1>Who should receive the quote?</h1><div className="portal-form two"><label><span>Company</span><input value={form.company} onChange={e=>patch({company:e.target.value})}/></label><label><span>Contact name</span><input value={form.contactName} onChange={e=>patch({contactName:e.target.value})}/></label><label><span>Email *</span><input type="email" value={form.email} onChange={e=>patch({email:e.target.value})}/></label><label><span>Phone</span><input value={form.phone} onChange={e=>patch({phone:e.target.value})}/></label><label className="full"><span>Reference / PO</span><input value={form.referenceNumber} onChange={e=>patch({referenceNumber:e.target.value})}/></label></div></>}
 {step===2&&<><p className="portal-kicker">ROUTE</p><h1>Where is it moving?</h1><div className="portal-form two"><label><span>Origin *</span><input value={form.originSearch} onChange={e=>patch({originSearch:e.target.value})} placeholder={form.mode==='air'?'Airport code or city':form.mode==='ocean'?'Port or city':'City or ZIP'}/></label><label><span>Destination *</span><input value={form.destinationSearch} onChange={e=>patch({destinationSearch:e.target.value})}/></label><label><span>Cargo ready date</span><input type="date" value={form.cargoReadyDate} onChange={e=>patch({cargoReadyDate:e.target.value})}/></label><label><span>Incoterm</span><input value={form.incoterm} onChange={e=>patch({incoterm:e.target.value})}/></label><label><span>Service type</span><select value={form.serviceType} onChange={e=>patch({serviceType:e.target.value})}><option value="">Select</option>{form.mode==='air'&&<><option value="airport">Airport to airport</option><option value="door">Door to door</option></>}{form.mode==='ocean'&&<><option value="lcl">LCL</option><option value="fcl">FCL</option></>}{form.mode==='ground'&&<><option value="ltl">LTL</option><option value="ftl">FTL</option></>}</select></label></div></>}
 {step===3&&<><div className="portal-title-row"><div><p className="portal-kicker">CARGO</p><h1>What are we moving?</h1></div><button onClick={()=>setCargo([...cargo,blankCargo()])}><Plus size={16}/> Add cargo</button></div><div className="cargo-cards">{cargo.map((c,index)=><article key={c.id}><header><div><Box/><b>Cargo line {index+1}</b></div>{cargo.length>1&&<button onClick={()=>setCargo(cargo.filter(x=>x.id!==c.id))}><Trash2 size={15}/></button>}</header><div className="cargo-grid"><label><span>Commodity</span><input value={c.commodity} onChange={e=>setCargo(cargo.map(x=>x.id===c.id?{...x,commodity:e.target.value}:x))}/></label><label><span>Package</span><select value={c.packagingType} onChange={e=>setCargo(cargo.map(x=>x.id===c.id?{...x,packagingType:e.target.value}:x))}><option>pallet</option><option>box</option><option>crate</option><option>skid</option></select></label><label><span>Qty</span><input type="number" value={c.qty} onChange={e=>setCargo(cargo.map(x=>x.id===c.id?{...x,qty:+e.target.value}:x))}/></label><label><span>Weight each</span><input type="number" value={c.weight} onChange={e=>setCargo(cargo.map(x=>x.id===c.id?{...x,weight:+e.target.value}:x))}/></label><label><span>Length</span><input type="number" value={c.length} onChange={e=>setCargo(cargo.map(x=>x.id===c.id?{...x,length:+e.target.value}:x))}/></label><label><span>Width</span><input type="number" value={c.width} onChange={e=>setCargo(cargo.map(x=>x.id===c.id?{...x,width:+e.target.value}:x))}/></label><label><span>Height</span><input type="number" value={c.height} onChange={e=>setCargo(cargo.map(x=>x.id===c.id?{...x,height:+e.target.value}:x))}/></label><label className="portal-check"><input type="checkbox" checked={c.stackable} onChange={e=>setCargo(cargo.map(x=>x.id===c.id?{...x,stackable:e.target.checked}:x))}/> Stackable</label><label className="portal-check"><input type="checkbox" checked={c.dangerousGoods} onChange={e=>setCargo(cargo.map(x=>x.id===c.id?{...x,dangerousGoods:e.target.checked}:x))}/> Dangerous goods</label></div></article>)}</div><div className="cargo-total"><div><span>Weight</span><b>{totals.kg.toFixed(1)} kg</b></div><div><span>Volume</span><b>{totals.cbm.toFixed(3)} CBM</b></div>{form.mode==='air'&&<div><span>Chargeable</span><b>{totals.chargeable.toFixed(1)} kg</b></div>}</div></>}
 {step===4&&<><p className="portal-kicker">ADDITIONAL SERVICES</p><h1>What else should we include?</h1><div className="service-grid">{services.map(([id,label])=><button className={extras.includes(id)?'selected':''} key={id} onClick={()=>toggle(id)}><Plus size={15}/><span>{label}</span>{extras.includes(id)&&<Check size={15}/>}</button>)}</div><div className="portal-form three"><label><span>Target rate</span><input type="number" value={form.targetRate} onChange={e=>patch({targetRate:e.target.value})}/></label><label><span>Currency</span><select value={form.targetCurrency} onChange={e=>patch({targetCurrency:e.target.value})}><option>USD</option><option>EUR</option></select></label><label><span>Rate basis</span><select value={form.targetUnit} onChange={e=>patch({targetUnit:e.target.value})}><option value="total">Total</option><option value="kg">Per kg</option><option value="cbm">Per CBM</option></select></label></div><div className="portal-inline"><label><input type="checkbox" checked={form.isBonded} onChange={e=>patch({isBonded:e.target.checked})}/> Bonded</label><label><input type="checkbox" checked={form.isFTZ} onChange={e=>patch({isFTZ:e.target.checked})}/> FTZ</label></div><label className="portal-textarea"><span>Special instructions</span><textarea value={form.specialInstructions} onChange={e=>patch({specialInstructions:e.target.value})}/></label></>}
 {step===5&&<><p className="portal-kicker">REVIEW</p><h1>Ready to submit?</h1><div className="review-route"><div><small>ORIGIN</small><b>{form.originSearch||'Not provided'}</b></div><ArrowRight/><div><small>DESTINATION</small><b>{form.destinationSearch||'Not provided'}</b></div></div><div className="review-grid"><article><span>Mode</span><b>{form.mode}</b></article><article><span>Cargo</span><b>{cargo.reduce((a,c)=>a+c.qty,0)} pieces</b></article><article><span>Weight</span><b>{totals.kg.toFixed(1)} kg</b></article><article><span>Volume</span><b>{totals.cbm.toFixed(3)} CBM</b></article><article><span>Extras</span><b>{extras.length}</b></article><article><span>Priority</span><b>{form.priority.replace('_',' ')}</b></article></div>{message&&<div className="portal-error">{message}</div>}</>}
 <footer className="portal-actions">{step>0?<button onClick={()=>setStep(step-1)}><ArrowLeft size={16}/> Back</button>:<span/>}{step<5?<button className="next" disabled={step===0&&!form.mode||step===1&&!form.email||step===2&&(!form.originSearch||!form.destinationSearch)} onClick={()=>setStep(step+1)}>Continue <ArrowRight size={16}/></button>:<button className="next" disabled={submitting} onClick={submit}>{submitting?'Submitting…':'Submit request'} <Check size={16}/></button>}</footer>
 </section></main></div>
}
