import { useMemo, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, FileUp, MapPin, Pencil, Plane, Plus, Ship, Trash2, Truck, Warehouse, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { freightLocations, type FreightLocation } from '../data/locations'

type Mode='air'|'ocean'|'ground'|'warehouse'|''
type Stop={company:string;address:string;city:string;state:string;zip:string;country:string;contact:string;phone:string;email:string;hours:string;appointment:boolean;liftgate:boolean;residential:boolean}
type Cargo={id:string;commodity:string;packagingType:string;qty:string;weight:string;weightUnit:'kg'|'lb';length:string;width:string;height:string;dimUnit:'cm'|'in';stackable:boolean;dangerousGoods:boolean;unNumber:string}
type Leg={id:string;type:string;label:string;sequence:number;from:Stop;to:Stop;notes:string;custom:boolean}
type Form={company:string;contactName:string;email:string;phone:string;referenceNumber:string;mode:Mode;serviceType:string;originSearch:string;originCode:string;originName:string;originCountry:string;destinationSearch:string;destinationCode:string;destinationName:string;destinationCountry:string;cargoReadyDate:string;estimatedDepartureDate:string;requestIntent:'quote'|'booking';incoterm:string;targetRate:string;targetCurrency:string;targetUnit:string;specialInstructions:string;priority:string}

const logo='https://raw.githubusercontent.com/N10ai/mip-tools/main/Untitled%20design%20-%201.png'
const steps=['Service','Contact','Route','Cargo','Journey','Documents','Review']
const modes=[{id:'air',label:'Air freight',icon:Plane},{id:'ocean',label:'Ocean freight',icon:Ship},{id:'ground',label:'Ground freight',icon:Truck},{id:'warehouse',label:'Warehousing',icon:Warehouse}] as const
const catalogs:Record<string,{id:string;label:string}[]>={
 air:[{id:'pickup',label:'Pickup / origin transfer'},{id:'airport_transfer',label:'Delivery to origin airline / airport'},{id:'customs_export',label:'Export customs / AES'},{id:'bonded',label:'Bonded transportation'},{id:'ftz',label:'FTZ handling'},{id:'insurance',label:'Cargo insurance'},{id:'packing',label:'Packing / crating'},{id:'destination_handling',label:'Destination airport handling'},{id:'customs_import',label:'Import customs clearance'},{id:'delivery',label:'Destination delivery'},{id:'warehouse',label:'Warehousing'}],
 ocean:[{id:'pickup',label:'Pickup / origin drayage'},{id:'port_transfer',label:'Delivery to port or CFS'},{id:'customs_export',label:'Export customs / documentation'},{id:'bonded',label:'Bonded transportation'},{id:'ftz',label:'FTZ handling'},{id:'insurance',label:'Cargo insurance'},{id:'packing',label:'Packing / crating'},{id:'destination_handling',label:'Destination port / CFS handling'},{id:'customs_import',label:'Import customs clearance'},{id:'delivery',label:'Destination delivery / drayage'},{id:'warehouse',label:'Warehousing'}],
 ground:[{id:'pickup',label:'Pickup and linehaul'},{id:'cross_dock',label:'Cross-dock / transfer'},{id:'bonded',label:'Bonded transportation'},{id:'ftz',label:'FTZ handling'},{id:'insurance',label:'Cargo insurance'},{id:'packing',label:'Packing / crating'},{id:'delivery',label:'Final delivery'},{id:'warehouse',label:'Warehousing'}],
 warehouse:[{id:'pickup',label:'Inbound pickup'},{id:'receiving',label:'Receiving and unloading'},{id:'storage',label:'Storage'},{id:'pick_pack',label:'Pick and pack'},{id:'distribution',label:'Distribution'},{id:'ftz',label:'FTZ handling'},{id:'bonded',label:'Bonded handling'}]
}
const emptyStop=():Stop=>({company:'',address:'',city:'',state:'',zip:'',country:'',contact:'',phone:'',email:'',hours:'',appointment:false,liftgate:false,residential:false})
const emptyCargo=():Cargo=>({id:crypto.randomUUID(),commodity:'',packagingType:'pallet',qty:'1',weight:'',weightUnit:'lb',length:'48',width:'40',height:'48',dimUnit:'in',stackable:true,dangerousGoods:false,unNumber:''})
const initial:Form={company:'',contactName:'',email:'',phone:'',referenceNumber:'',mode:'',serviceType:'',originSearch:'',originCode:'',originName:'',originCountry:'',destinationSearch:'',destinationCode:'',destinationName:'',destinationCountry:'',cargoReadyDate:'',estimatedDepartureDate:'',requestIntent:'quote',incoterm:'',targetRate:'',targetCurrency:'USD',targetUnit:'total',specialInstructions:'',priority:'best_value'}

function LocationField({label,mode,value,onSelect}:{label:string;mode:Mode;value:string;onSelect:(value:FreightLocation|string)=>void}){const[open,setOpen]=useState(false);const type=mode==='air'?'airport':mode==='ocean'?'port':'city';const matches=useMemo(()=>{const q=value.toLowerCase().trim();return freightLocations.filter(x=>x.type===type&&(!q||[x.code,x.name,x.city,x.country].join(' ').toLowerCase().includes(q))).slice(0,12)},[value,type]);return <label className="location-field"><span>{label}</span><input value={value} onFocus={()=>setOpen(true)} onBlur={()=>setTimeout(()=>setOpen(false),150)} onChange={e=>{onSelect(e.target.value);setOpen(true)}} placeholder={mode==='air'?'Airport code or city':mode==='ocean'?'Port, UN/LOCODE or city':'City, state or ZIP'}/>{open&&matches.length>0&&<div className="location-menu">{matches.map(x=><button type="button" key={`${x.type}-${x.code}`} onMouseDown={e=>e.preventDefault()} onClick={()=>{onSelect(x);setOpen(false)}}><b>{x.code}</b><div><strong>{x.name}</strong><small>{x.city}, {x.country}</small></div></button>)}</div>}</label>}

function StopEditor({title,value,onChange}:{title:string;value:Stop;onChange:(value:Stop)=>void}){const patch=(p:Partial<Stop>)=>onChange({...value,...p});return <div className="journey-stop"><h4><MapPin size={15}/>{title}</h4><div className="portal-form two"><label><span>Company / location</span><input value={value.company} onChange={e=>patch({company:e.target.value})}/></label><label><span>Street address</span><input value={value.address} onChange={e=>patch({address:e.target.value})}/></label><label><span>City</span><input value={value.city} onChange={e=>patch({city:e.target.value})}/></label><label><span>State / province</span><input value={value.state} onChange={e=>patch({state:e.target.value})}/></label><label><span>ZIP / postal</span><input value={value.zip} onChange={e=>patch({zip:e.target.value})}/></label><label><span>Country</span><input value={value.country} onChange={e=>patch({country:e.target.value})}/></label><label><span>Contact</span><input value={value.contact} onChange={e=>patch({contact:e.target.value})}/></label><label><span>Phone</span><input value={value.phone} onChange={e=>patch({phone:e.target.value})}/></label><label className="full"><span>Hours / ready time</span><input value={value.hours} onChange={e=>patch({hours:e.target.value})}/></label></div><div className="portal-inline"><label><input type="checkbox" checked={value.appointment} onChange={e=>patch({appointment:e.target.checked})}/> Appointment</label><label><input type="checkbox" checked={value.liftgate} onChange={e=>patch({liftgate:e.target.checked})}/> Liftgate</label><label><input type="checkbox" checked={value.residential} onChange={e=>patch({residential:e.target.checked})}/> Residential / limited access</label></div></div>}

export function PublicRequestPortalV2(){
 const[step,setStep]=useState(0),[form,setForm]=useState<Form>(initial),[cargo,setCargo]=useState<Cargo[]>([emptyCargo()]),[legs,setLegs]=useState<Leg[]>([]),[files,setFiles]=useState<File[]>([]),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState(''),[customName,setCustomName]=useState('')
 const patch=(p:Partial<Form>)=>setForm(v=>({...v,...p}))
 const updateCargo=(id:string,p:Partial<Cargo>)=>setCargo(rows=>rows.map(x=>x.id===id?{...x,...p}:x))
 const updateLeg=(id:string,p:Partial<Leg>)=>setLegs(rows=>rows.map(x=>x.id===id?{...x,...p}:x))
 const moveLeg=(index:number,direction:-1|1)=>setLegs(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next.map((x,i)=>({...x,sequence:i+1}))})
 const addLeg=(item:{id:string;label:string},custom=false)=>setLegs(current=>[...current,{id:crypto.randomUUID(),type:item.id,label:item.label,sequence:current.length+1,from:emptyStop(),to:emptyStop(),notes:'',custom}])
 const totals=useMemo(()=>{let kg=0,cbm=0;for(const c of cargo){const qty=Number(c.qty)||0,w=Number(c.weight)||0,l=Number(c.length)||0,wd=Number(c.width)||0,h=Number(c.height)||0,f=c.dimUnit==='in'?2.54:1;kg+=(c.weightUnit==='lb'?w*.453592:w)*qty;cbm+=(l*f*wd*f*h*f/1e6)*qty}return{kg,cbm,chargeable:Math.max(kg,cbm*167)}},[cargo])
 const setLocation=(side:'origin'|'destination',value:FreightLocation|string)=>{if(typeof value==='string'){patch(side==='origin'?{originSearch:value,originCode:'',originName:value,originCountry:''}:{destinationSearch:value,destinationCode:'',destinationName:value,destinationCountry:''});return}patch(side==='origin'?{originSearch:`${value.code} — ${value.name}`,originCode:value.code,originName:value.name,originCountry:value.country}:{destinationSearch:`${value.code} — ${value.name}`,destinationCode:value.code,destinationName:value.name,destinationCountry:value.country})}
 const uploadDocuments=async(requestId:string)=>{for(const file of files){const path=`${requestId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const{error}=await supabase.storage.from('quote-request-documents').upload(path,file,{contentType:file.type,upsert:false});if(!error)await supabase.from('quote_request_documents').insert({quote_request_id:requestId,file_name:file.name,file_type:file.type||null,file_size:file.size,storage_path:path,document_type:'customer_upload'})}}
 const submit=async()=>{setSubmitting(true);setMessage('');const firstFrom=legs.find(l=>l.from.address||l.from.city)?.from;const lastTo=[...legs].reverse().find(l=>l.to.address||l.to.city)?.to;const payload:any={...form,requestIntent:form.requestIntent,estimatedDepartureDate:form.estimatedDepartureDate,serviceLegs:legs.map(l=>({id:l.id,type:l.type,label:l.label,sequence:l.sequence,origin:[l.from.company,l.from.address,l.from.city,l.from.state,l.from.zip,l.from.country].filter(Boolean).join(', '),destination:[l.to.company,l.to.address,l.to.city,l.to.state,l.to.zip,l.to.country].filter(Boolean).join(', '),details:{from:l.from,to:l.to,notes:l.notes,custom:l.custom}})),targetRate:{amount:Number(form.targetRate)||null,currency:form.targetCurrency,unit:form.targetUnit},cargo:cargo.map(c=>({commodity:c.commodity,packagingType:c.packagingType,cargoType:c.dangerousGoods?'dg':'general',dangerousGoods:c.dangerousGoods,unNumber:c.unNumber||null,qty:Number(c.qty)||0,weight:{value:Number(c.weight)||0,unit:c.weightUnit},dimensions:{length:{value:Number(c.length)||0,unit:c.dimUnit},width:{value:Number(c.width)||0,unit:c.dimUnit},height:{value:Number(c.height)||0,unit:c.dimUnit}},stackable:c.stackable})),totals:{weight:{kg:{value:+totals.kg.toFixed(2),unit:'kg'}},volume:{cbm:{value:+totals.cbm.toFixed(3),unit:'m3'}},chargeableWeight:{kg:{value:+totals.chargeable.toFixed(2),unit:'kg'}}},includeInland:legs.length>0,pickup:firstFrom,delivery:lastTo};const{data,error}=await supabase.functions.invoke('submit-quote-request',{body:payload});if(error){setSubmitting(false);setMessage(error.message);return}await uploadDocuments(data.requestId);setSubmitting(false);setMessage(`SUCCESS:${data.requestNumber}`)}
 if(message.startsWith('SUCCESS:'))return <div className="public-portal"><header className="portal-header"><img src={logo}/><div><b>MIP Cargo Express</b><span>Freight solutions made simple</span></div></header><main className="portal-success"><div><Check/></div><p>REQUEST RECEIVED</p><h1>Thank you.</h1><h2>Your reference is {message.split(':')[1]}</h2><span>Our pricing team will contact you shortly.</span><button onClick={()=>location.reload()}>Submit another request</button></main></div>
 return <div className="public-portal portal-v2"><header className="portal-header"><img src={logo}/><div><b>MIP Cargo Express</b><span>Freight solutions made simple</span></div><a href="#/">Internal portal</a></header><div className="portal-progress"><div style={{width:`${step/(steps.length-1)*100}%`}}/></div><main className="portal-shell"><aside>{steps.map((s,i)=><div className={i===step?'active':i<step?'done':''} key={s}><i>{i<step?<Check size={13}/>:i+1}</i><span>{s}</span></div>)}</aside><section className="portal-stage">
 {step===0&&<><p className="portal-kicker">REQUEST A FREIGHT QUOTE</p><h1>What do you need to move?</h1><div className="mode-grid">{modes.map(({id,label,icon:Icon})=><button type="button" className={form.mode===id?'selected':''} onClick={()=>{patch({mode:id});setLegs([])}} key={id}><Icon/><b>{label}</b>{form.mode===id&&<i><Check size={14}/></i>}</button>)}</div><div className="intent-card"><div><b>What should we prepare?</b><span>Choose a rate request or ask us to confirm an actual booking.</span></div><div><button className={form.requestIntent==='quote'?'selected':''} onClick={()=>patch({requestIntent:'quote'})}>Quote / rate only</button><button className={form.requestIntent==='booking'?'selected':''} onClick={()=>patch({requestIntent:'booking'})}>Booking request</button></div></div></>}
 {step===1&&<><p className="portal-kicker">CONTACT</p><h1>Who should receive the quote?</h1><div className="portal-form two"><label><span>Company</span><input value={form.company} onChange={e=>patch({company:e.target.value})}/></label><label><span>Contact name</span><input value={form.contactName} onChange={e=>patch({contactName:e.target.value})}/></label><label><span>Email *</span><input type="email" value={form.email} onChange={e=>patch({email:e.target.value})}/></label><label><span>Phone</span><input value={form.phone} onChange={e=>patch({phone:e.target.value})}/></label><label className="full"><span>Reference / PO</span><input value={form.referenceNumber} onChange={e=>patch({referenceNumber:e.target.value})}/></label></div></>}
 {step===2&&<><p className="portal-kicker">ROUTE</p><h1>Where and when is it moving?</h1><div className="portal-form two"><LocationField label="Origin *" mode={form.mode} value={form.originSearch} onSelect={x=>setLocation('origin',x)}/><LocationField label="Destination *" mode={form.mode} value={form.destinationSearch} onSelect={x=>setLocation('destination',x)}/><label><span>Cargo ready date</span><input type="date" value={form.cargoReadyDate} onChange={e=>patch({cargoReadyDate:e.target.value})}/></label><label><span>Estimated departure</span><input type="date" value={form.estimatedDepartureDate} onChange={e=>patch({estimatedDepartureDate:e.target.value})}/></label><label><span>Incoterm</span><input value={form.incoterm} onChange={e=>patch({incoterm:e.target.value})}/></label><label><span>Service type</span><input value={form.serviceType} onChange={e=>patch({serviceType:e.target.value})} placeholder="Airport-airport, LCL, FTL..."/></label></div></>}
 {step===3&&<><p className="portal-kicker">CARGO</p><h1>Describe the cargo</h1><div className="cargo-builder">{cargo.map((c,index)=><article key={c.id}><header><b>Cargo line {index+1}</b>{cargo.length>1&&<button onClick={()=>setCargo(v=>v.filter(x=>x.id!==c.id))}><Trash2 size={15}/></button>}</header><div className="cargo-fields"><label className="commodity"><span>Commodity</span><input value={c.commodity} onChange={e=>updateCargo(c.id,{commodity:e.target.value})}/></label><label><span>Qty</span><input inputMode="decimal" value={c.qty} placeholder="0" onChange={e=>updateCargo(c.id,{qty:e.target.value})}/></label><label><span>Package</span><select value={c.packagingType} onChange={e=>updateCargo(c.id,{packagingType:e.target.value})}><option>pallet</option><option>box</option><option>crate</option><option>drum</option><option>piece</option></select></label><label className="weight-field"><span>Weight each</span><div><input inputMode="decimal" value={c.weight} placeholder="0" onChange={e=>updateCargo(c.id,{weight:e.target.value})}/><select value={c.weightUnit} onChange={e=>updateCargo(c.id,{weightUnit:e.target.value as 'kg'|'lb'})}><option>lb</option><option>kg</option></select></div></label><label className="dimension-field"><span>Dimensions</span><div><input inputMode="decimal" value={c.length} placeholder="L" onChange={e=>updateCargo(c.id,{length:e.target.value})}/><input inputMode="decimal" value={c.width} placeholder="W" onChange={e=>updateCargo(c.id,{width:e.target.value})}/><input inputMode="decimal" value={c.height} placeholder="H" onChange={e=>updateCargo(c.id,{height:e.target.value})}/><select value={c.dimUnit} onChange={e=>updateCargo(c.id,{dimUnit:e.target.value as 'cm'|'in'})}><option>in</option><option>cm</option></select></div></label></div><div className="portal-inline"><label><input type="checkbox" checked={c.stackable} onChange={e=>updateCargo(c.id,{stackable:e.target.checked})}/> Stackable</label><label><input type="checkbox" checked={c.dangerousGoods} onChange={e=>updateCargo(c.id,{dangerousGoods:e.target.checked})}/> Dangerous goods</label>{c.dangerousGoods&&<input className="un-input" value={c.unNumber} placeholder="UN number" onChange={e=>updateCargo(c.id,{unNumber:e.target.value})}/>}</div></article>)}</div><button className="add-cargo" onClick={()=>setCargo(v=>[...v,emptyCargo()])}><Plus size={16}/>Add cargo line</button><div className="cargo-totals"><span>Total weight <b>{totals.kg.toFixed(1)} kg</b></span><span>Volume <b>{totals.cbm.toFixed(3)} CBM</b></span><span>Air chargeable <b>{totals.chargeable.toFixed(1)} kg</b></span></div></>}
 {step===4&&<><p className="portal-kicker">SERVICE JOURNEY</p><h1>Build the complete movement</h1><p className="portal-copy">Every transport service has a from and a to location. Add, rename, edit, remove, and reorder services.</p><div className="service-grid">{(catalogs[form.mode]||[]).map(item=><button type="button" key={item.id} onClick={()=>addLeg(item)}><Plus size={15}/><span>{item.label}</span></button>)}</div><div className="custom-service-add"><input value={customName} placeholder="Custom service name" onChange={e=>setCustomName(e.target.value)}/><button disabled={!customName.trim()} onClick={()=>{addLeg({id:`custom_${Date.now()}`,label:customName.trim()},true);setCustomName('')}}><Plus size={15}/>Add custom service</button></div><div className="journey-editor">{legs.map((leg,index)=><article key={leg.id}><header><i>{index+1}</i><input value={leg.label} onChange={e=>updateLeg(leg.id,{label:e.target.value})}/><span>{leg.custom?'Custom service':leg.type.replaceAll('_',' ')}</span><div><button disabled={index===0} onClick={()=>moveLeg(index,-1)}><ArrowUp size={14}/></button><button disabled={index===legs.length-1} onClick={()=>moveLeg(index,1)}><ArrowDown size={14}/></button><button onClick={()=>setLegs(v=>v.filter(x=>x.id!==leg.id).map((x,i)=>({...x,sequence:i+1})))}><Trash2 size={14}/></button></div></header><div className="journey-pair"><StopEditor title="From / collect at" value={leg.from} onChange={value=>updateLeg(leg.id,{from:value})}/><ArrowRight className="journey-arrow"/><StopEditor title="To / deliver at" value={leg.to} onChange={value=>updateLeg(leg.id,{to:value})}/></div><label className="portal-textarea"><span>Service notes</span><textarea value={leg.notes} onChange={e=>updateLeg(leg.id,{notes:e.target.value})}/></label></article>)}{!legs.length&&<div className="journey-empty">No additional services selected. Main freight will still be requested.</div>}</div><div className="portal-form three"><label><span>Target rate</span><input inputMode="decimal" value={form.targetRate} placeholder="0" onChange={e=>patch({targetRate:e.target.value})}/></label><label><span>Currency</span><select value={form.targetCurrency} onChange={e=>patch({targetCurrency:e.target.value})}><option>USD</option><option>EUR</option></select></label><label><span>Rate basis</span><select value={form.targetUnit} onChange={e=>patch({targetUnit:e.target.value})}><option value="total">Total shipment</option><option value="kg">Per kg</option><option value="lb">Per lb</option><option value="cbm">Per CBM</option><option value="container">Per container</option><option value="pallet">Per pallet</option></select></label></div><label className="portal-textarea"><span>Special instructions</span><textarea value={form.specialInstructions} onChange={e=>patch({specialInstructions:e.target.value})}/></label></>}
 {step===5&&<><p className="portal-kicker">DOCUMENTS</p><h1>Add supporting files</h1><label className="document-drop"><FileUp size={28}/><b>Choose documents</b><span>PDF, images, Word, or Excel — 10 MB each</span><input type="file" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).filter(f=>f.size<=10_485_760))}/></label>{files.length>0&&<div className="document-list">{files.map((file,i)=><div key={`${file.name}-${i}`}><FileUp size={16}/><span>{file.name}<small>{(file.size/1024/1024).toFixed(2)} MB</small></span><button onClick={()=>setFiles(files.filter((_,n)=>n!==i))}><X size={15}/></button></div>)}</div>}</>}
 {step===6&&<><p className="portal-kicker">REVIEW</p><h1>Ready to submit?</h1><div className="review-route"><div><small>ORIGIN</small><b>{form.originSearch||'Not provided'}</b></div><ArrowRight/><div><small>DESTINATION</small><b>{form.destinationSearch||'Not provided'}</b></div></div><div className="review-grid"><article><span>Intent</span><b>{form.requestIntent==='booking'?'Booking request':'Quote / rate'}</b></article><article><span>Departure</span><b>{form.estimatedDepartureDate||'Flexible'}</b></article><article><span>Cargo</span><b>{cargo.reduce((a,c)=>a+(Number(c.qty)||0),0)} pieces</b></article><article><span>Weight</span><b>{totals.kg.toFixed(1)} kg</b></article><article><span>Services</span><b>{legs.length}</b></article><article><span>Documents</span><b>{files.length}</b></article></div>{legs.length>0&&<div className="review-journey">{legs.map((leg,i)=><div key={leg.id}><i>{i+1}</i><b>{leg.label}</b><small>{[leg.from.city,leg.from.state].filter(Boolean).join(', ')||'From pending'} → {[leg.to.city,leg.to.state].filter(Boolean).join(', ')||'To pending'}</small></div>)}</div>}{message&&<div className="portal-error">{message}</div>}</>}
 <footer className="portal-actions">{step>0?<button onClick={()=>setStep(step-1)}><ArrowLeft size={16}/>Back</button>:<span/>}{step<steps.length-1?<button className="next" disabled={step===0&&!form.mode||step===1&&!form.email||step===2&&(!form.originSearch||!form.destinationSearch)} onClick={()=>setStep(step+1)}>Continue<ArrowRight size={16}/></button>:<button className="next" disabled={submitting} onClick={submit}>{submitting?'Submitting…':'Submit request'}<Check size={16}/></button>}</footer>
 </section></main></div>
}
