import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ChevronDown, ChevronRight, FileDown, FileText, Library, Mail, Pencil, Plus, Save, Send, Trash2, X } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { generateQuotePdf } from '../lib/quotePdf'
import { Button, EmptyState } from './ui'

type Basis='flat'|'per_actual_kg'|'per_chargeable_kg'|'per_lb'|'per_cbm'|'per_piece'|'per_pallet'|'per_container'
type Cargo={id:string;quantity:number;packaging_type:string|null;commodity:string|null;weight_value:number|null;weight_unit:string|null;length_value:number|null;width_value:number|null;height_value:number|null;dimension_unit:string|null}
type Charge={id:string;description:string;basis:Basis;quantity:number;rate:number;sellRate:number;minimum:number;cost:number;sell:number;autoQuantity:boolean;source?:string}
type QuoteRow={id:string;quote_number:string;customer_name:string|null;status:string;quote_data:any;quote_request_id:string|null;created_at:string}
type RequestRow={customer_company:string|null;contact_name:string|null;contact_email:string;customer_reference:string|null;mode:string|null;service_type:string|null;direction:string|null;origin_code:string|null;origin_name:string|null;destination_code:string|null;destination_name:string|null;incoterm:string|null}
type SelectedRate={response_data:any;vendors?:{company?:string}|null}
type ChargeLibraryItem={id:string;name:string;type:string;rate:number;qty:number;minimum:number}
type ServiceTemplate={id:string;name:string;icon:string;chargeName:string;defaultSell:number;note:string}

const basisLabels:Record<Basis,string>={flat:'Flat',per_actual_kg:'Actual kg',per_chargeable_kg:'Chargeable kg',per_lb:'Lb',per_cbm:'CBM',per_piece:'Piece',per_pallet:'Pallet',per_container:'Container'}
const defaults:ServiceTemplate[]=[
 {id:'pickup',name:'Pickup',icon:'↗',chargeName:'Pickup',defaultSell:0,note:'Origin pickup service'},
 {id:'delivery',name:'Delivery',icon:'↘',chargeName:'Delivery',defaultSell:0,note:'Final delivery service'},
 {id:'customs',name:'Customs Clearance',icon:'✓',chargeName:'Customs Clearance',defaultSell:95,note:'Brokerage and entry processing'},
 {id:'insurance',name:'Cargo Insurance',icon:'◇',chargeName:'Cargo Insurance',defaultSell:0,note:'Optional cargo insurance'},
 {id:'storage',name:'Storage',icon:'▣',chargeName:'Storage',defaultSell:0,note:'Warehouse storage'},
 {id:'liftgate',name:'Liftgate',icon:'⇅',chargeName:'Liftgate',defaultSell:0,note:'Liftgate equipment'},
]
const text=(v:any,f='')=>v==null||v===''?f:String(v)
const number=(v:any)=>Number(v)||0
const money=(n:number,c='USD')=>{try{return new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number.isFinite(n)?n:0)}catch{return `$${(n||0).toFixed(2)}`}}
const route=(a:string,b:string)=>`${a||'Origin'} → ${b||'Destination'}`
const normalizeBasis=(v:string):Basis=>({flat:'flat',per_chargeable_kg:'per_chargeable_kg',per_kg:'per_actual_kg',per_actual_kg:'per_actual_kg',per_lb:'per_lb',per_cbm:'per_cbm',per_piece:'per_piece',per_pallet:'per_pallet',per_container:'per_container'} as Record<string,Basis>)[v]||'flat'
const blankCharge=(description='New charge',sellRate=0,source?:string):Charge=>({id:crypto.randomUUID(),description,basis:'flat',quantity:1,rate:0,sellRate,minimum:0,cost:0,sell:sellRate,autoQuantity:false,source})
function metrics(cargo:Cargo[]){let actualKg=0,cbm=0,pieces=0,pallets=0,containers=0;for(const c of cargo){const q=number(c.quantity)||1,w=number(c.weight_value),wu=text(c.weight_unit,'kg').toLowerCase(),du=text(c.dimension_unit,'cm').toLowerCase(),f=du==='in'?2.54:1;pieces+=q;actualKg+=(wu==='lb'?w*.453592:w)*q;cbm+=number(c.length_value)*f*number(c.width_value)*f*number(c.height_value)*f/1e6*q;const p=text(c.packaging_type).toLowerCase();if(p.includes('pallet'))pallets+=q;if(p.includes('container'))containers+=q}return{actualKg,chargeableKg:Math.max(actualKg,cbm*167),cbm,pieces,pallets,containers}}
const quantityFor=(b:Basis,m:ReturnType<typeof metrics>)=>({flat:1,per_actual_kg:m.actualKg,per_chargeable_kg:m.chargeableKg,per_lb:m.actualKg*2.20462,per_cbm:m.cbm,per_piece:m.pieces,per_pallet:m.pallets,per_container:m.containers}[b]||1)
function calculate(c:Charge,m:ReturnType<typeof metrics>){const q=c.autoQuantity?quantityFor(c.basis,m):number(c.quantity),rate=number(c.rate),sellRate=number(c.sellRate);return{...c,quantity:q,rate,sellRate,cost:Math.max(q*rate,number(c.minimum)),sell:q*sellRate}}
function normalizeCargo(rows:any[]):Cargo[]{return(rows||[]).map((c:any)=>({id:c.id||crypto.randomUUID(),quantity:number(c.quantity??c.qty)||1,packaging_type:text(c.packaging_type??c.desc,'piece'),commodity:text(c.commodity??c.desc,'Cargo'),weight_value:number(c.weight_value??c.weight),weight_unit:text(c.weight_unit??c.wUnit,'kg'),length_value:number(c.length_value??c.l),width_value:number(c.width_value??c.w),height_value:number(c.height_value??c.h),dimension_unit:text(c.dimension_unit??c.dUnit,'cm')}))}
function normalizeCharges(rows:any[],m:ReturnType<typeof metrics>):Charge[]{return(rows||[]).map((c:any)=>{const basis=normalizeBasis(text(c.basis??c.type??c.unit,'flat')),quantity=number(c.quantity??c.qty)||quantityFor(basis,m),rate=number(c.rate)||(basis==='flat'?number(c.cost??c.amount):0),sell=number(c.sell??c.amount)||number(c.cost)||quantity*rate,sellRate=number(c.sellRate??c.sell_rate)||(quantity?sell/quantity:sell)||rate;return calculate({id:c.id||crypto.randomUUID(),description:text(c.description??c.name,'Charge'),basis,quantity,rate,sellRate,minimum:number(c.minimum??c.min),cost:0,sell:0,autoQuantity:c.autoQuantity??basis!=='flat',source:c.source},m)})}

export function QuoteWorkspaceV5(){const[params,setParams]=useSearchParams();const id=params.get('quote');if(!id)return <div className="qw4-empty"><EmptyState icon={<FileText size={28}/>} title="No quote selected" copy="Choose a quote from the queue."/></div>;return <Editor quoteId={id} onClose={()=>setParams({})}/>}

function Editor({quoteId,onClose}:{quoteId:string;onClose:()=>void}){
 const[quote,setQuote]=useState<QuoteRow|null>(null),[request,setRequest]=useState<RequestRow|null>(null),[selectedRate,setSelectedRate]=useState<SelectedRate|null>(null)
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[pdfBusy,setPdfBusy]=useState(false),[message,setMessage]=useState('')
 const[cargo,setCargo]=useState<Cargo[]>([]),[charges,setCharges]=useState<Charge[]>([]),[services,setServices]=useState<string[]>([])
 const[serviceLibrary,setServiceLibrary]=useState<ServiceTemplate[]>(()=>{try{return JSON.parse(localStorage.getItem('mip-service-library')||'null')||defaults}catch{return defaults}})
 const[chargeLibrary,setChargeLibrary]=useState<ChargeLibraryItem[]>([]),[libraryOpen,setLibraryOpen]=useState(false),[serviceEditorOpen,setServiceEditorOpen]=useState(false)
 const[editingService,setEditingService]=useState<ServiceTemplate|null>(null),[editingCharge,setEditingCharge]=useState<ChargeLibraryItem|null>(null)
 const[detailsOpen,setDetailsOpen]=useState(false),[servicesOpen,setServicesOpen]=useState(true),[termsOpen,setTermsOpen]=useState(false)
 const[customerName,setCustomerName]=useState(''),[customerEmail,setCustomerEmail]=useState(''),[customerReference,setCustomerReference]=useState(''),[commodity,setCommodity]=useState(''),[mode,setMode]=useState(''),[direction,setDirection]=useState(''),[serviceType,setServiceType]=useState(''),[incoterm,setIncoterm]=useState(''),[origin,setOrigin]=useState(''),[destination,setDestination]=useState('')
 const[currency,setCurrency]=useState('USD'),[validUntil,setValidUntil]=useState(''),[transit,setTransit]=useState(''),[carrier,setCarrier]=useState(''),[routing,setRouting]=useState(''),[frequency,setFrequency]=useState(''),[customerNotes,setCustomerNotes]=useState(''),[terms,setTerms]=useState('Rates subject to space and equipment availability. Duties, taxes, inspections, storage, demurrage and detention are excluded unless specifically stated.')
 const m=useMemo(()=>metrics(cargo),[cargo]);const totals=useMemo(()=>{const cost=charges.reduce((s,c)=>s+c.cost,0),sell=charges.reduce((s,c)=>s+c.sell,0),profit=sell-cost;return{cost,sell,profit,margin:sell?profit/sell*100:0}},[charges]);const generated=Boolean(quote?.quote_request_id)
 useEffect(()=>{(async()=>{setLoading(true);const[{data:q,error},{data:lib}]=await Promise.all([supabase.from('quotes').select('*').eq('id',quoteId).single(),supabase.from('charge_library').select('*').order('name')]);if(error||!q){setMessage(error?.message||'Quote not found');setLoading(false);return}setChargeLibrary((lib||[]) as ChargeLibraryItem[]);const qr=q as QuoteRow,d=qr.quote_data||{};setQuote(qr);let req:any=null,rfq:any=null,cargoRows=normalizeCargo(d.cargo||[]);if(qr.quote_request_id){const[{data:r},{data:cg},{data:sr}]=await Promise.all([supabase.from('quote_requests').select('*').eq('id',qr.quote_request_id).maybeSingle(),supabase.from('quote_request_cargo').select('*').eq('quote_request_id',qr.quote_request_id).order('line_number'),supabase.from('vendor_rfqs').select('response_data,vendors(company)').eq('quote_request_id',qr.quote_request_id).eq('status','selected').limit(1).maybeSingle()]);req=r;rfq=sr;if((cg||[]).length)cargoRows=normalizeCargo(cg||[])}setRequest(req);setSelectedRate(rfq);setCargo(cargoRows);const mm=metrics(cargoRows),response=rfq?.response_data||d.vendor?.response||{};setCustomerName(text(qr.customer_name,req?.customer_company||req?.contact_name||'Customer'));setCustomerEmail(text(d.customerEmail,req?.contact_email));setCustomerReference(text(d.customerReference,req?.customer_reference));setCommodity(text(d.commodity,cargoRows.map(x=>x.commodity).filter(Boolean).join(', ')));setMode(text(d.mode,req?.mode));setDirection(text(d.direction,req?.direction));setServiceType(text(d.serviceType,req?.service_type));setIncoterm(text(d.incoterm,req?.incoterm));setOrigin(text(d.origin,req?.origin_code||req?.origin_name));setDestination(text(d.destination,req?.destination_code||req?.destination_name));setCurrency(text(d.currency,response.currency||'USD'));setValidUntil(text(d.validUntil,response.valid_until));setTransit(text(d.transit,response.transit));setCarrier(text(d.carrier,response.carrier||d.vendor?.name||rfq?.vendors?.company));setRouting(text(d.routing,response.routing));setFrequency(text(d.frequency,response.frequency));setCustomerNotes(text(d.customerNotes));setTerms(text(d.terms,terms));setServices(Array.isArray(d.services)?d.services:[]);setCharges(normalizeCharges(d.charges||response.charges||[],mm));setDetailsOpen(!qr.quote_request_id);setLoading(false)})()},[quoteId])
 useEffect(()=>setCharges(rows=>rows.map(c=>calculate(c,m))),[m.actualKg,m.cbm,m.pieces,m.pallets,m.containers])
 const patchCharge=(id:string,patch:Partial<Charge>)=>setCharges(rows=>rows.map(c=>c.id===id?calculate({...c,...patch},m):c))
 const toggleService=(service:ServiceTemplate)=>{const active=services.includes(service.id);setServices(v=>active?v.filter(x=>x!==service.id):[...v,service.id]);if(active)setCharges(v=>v.filter(x=>x.source!==`service:${service.id}`));else if(!charges.some(x=>x.source===`service:${service.id}`))setCharges(v=>[...v,calculate(blankCharge(service.chargeName,service.defaultSell,`service:${service.id}`),m)])}
 const persistServices=(next:ServiceTemplate[])=>{setServiceLibrary(next);localStorage.setItem('mip-service-library',JSON.stringify(next))}
 const saveService=()=>{if(!editingService)return;const exists=serviceLibrary.some(x=>x.id===editingService.id);persistServices(exists?serviceLibrary.map(x=>x.id===editingService.id?editingService:x):[...serviceLibrary,editingService]);setEditingService(null)}
 const deleteService=(id:string)=>{persistServices(serviceLibrary.filter(x=>x.id!==id));setServices(v=>v.filter(x=>x!==id));setCharges(v=>v.filter(x=>x.source!==`service:${id}`))}
 const saveChargeLibrary=async()=>{if(!editingCharge)return;const payload={name:editingCharge.name,type:editingCharge.type,rate:number(editingCharge.rate),qty:number(editingCharge.qty)||1,minimum:number(editingCharge.minimum)};const result=editingCharge.id?await supabase.from('charge_library').update(payload).eq('id',editingCharge.id):await supabase.from('charge_library').insert(payload);if(result.error){alert(result.error.message);return}const{data}=await supabase.from('charge_library').select('*').order('name');setChargeLibrary((data||[]) as ChargeLibraryItem[]);setEditingCharge(null)}
 const deleteChargeLibrary=async(id:string)=>{await supabase.from('charge_library').delete().eq('id',id);setChargeLibrary(v=>v.filter(x=>x.id!==id))}
 const addFromLibrary=(item:ChargeLibraryItem)=>{const basis=normalizeBasis(item.type);setCharges(v=>[...v,calculate({id:crypto.randomUUID(),description:item.name,basis,quantity:item.qty||quantityFor(basis,m),rate:item.rate,sellRate:item.rate,minimum:item.minimum,cost:0,sell:0,autoQuantity:basis!=='flat',source:'library'},m)]);setLibraryOpen(false)}
 const buildData=()=>({...quote?.quote_data,customerEmail,customerReference,commodity,mode,direction,serviceType,incoterm,origin,destination,route:route(origin,destination),currency,validUntil,transit,carrier,routing,frequency,customerNotes,terms,cargo,metrics:m,charges,services,totals,vendor:{...quote?.quote_data?.vendor,name:selectedRate?.vendors?.company||quote?.quote_data?.vendor?.name,response:selectedRate?.response_data||quote?.quote_data?.vendor?.response}})
 const save=async(status=quote?.status||'draft')=>{if(!quote)return;setSaving(true);const{data,error}=await supabase.from('quotes').update({customer_name:customerName,status,quote_data:buildData()}).eq('id',quote.id).select('*').single();setSaving(false);if(error)setMessage(error.message);else{setQuote(data as QuoteRow);setMessage(status==='sent'?'Quote marked sent.':'Quote saved.')}}
 const createPdf=async()=>{if(!quote)return;setPdfBusy(true);try{await generateQuotePdf({quoteNumber:quote.quote_number||'Quote',customer:customerName,customerEmail,customerReference,route:route(origin,destination),status:quote.status,issued:new Date(quote.created_at).toLocaleDateString('en-US'),validity:validUntil,currency,mode:[mode,direction].filter(Boolean).join(' '),service:serviceType,incoterm,commodity,pieces:m.pieces,actualWeight:m.actualKg,chargeableWeight:m.chargeableKg,cbm:m.cbm,carrier,transit,services:services.map(id=>serviceLibrary.find(x=>x.id===id)?.name||id),charges:charges.map(c=>({description:c.description,basis:basisLabels[c.basis],quantity:c.quantity,unitRate:c.sellRate,amount:c.sell})),total:totals.sell,notes:customerNotes,terms})}finally{setPdfBusy(false)}}
 if(loading)return <div className="qw4-loading">Loading quote…</div>
 const workflow=[['Request',generated],['RFQs',Boolean(selectedRate||quote?.quote_data?.vendor)],['Vendor',Boolean(selectedRate||quote?.quote_data?.vendor?.name)],['Review',true],['Sent',quote?.status==='sent']]
 return <div className="qw4-shell qw5-shell"><header className="qw4-topbar"><button onClick={onClose}><ArrowLeft size={16}/>Quotes</button><div><small>{generated?'AUTOMATED QUOTE':'MANUAL QUOTE'}</small><h1>{quote?.quote_number||'Quote'}</h1><p>{customerName} · {route(origin,destination)}</p></div><div className="qw4-actions"><Button variant="secondary" disabled={saving} onClick={()=>save()}><Save size={15}/>Save</Button><Button variant="secondary" disabled={pdfBusy} onClick={createPdf}><FileDown size={15}/>{pdfBusy?'Generating…':'PDF'}</Button><Button variant="secondary" onClick={()=>location.href=`mailto:${customerEmail}`}><Mail size={15}/>Email</Button><Button disabled={saving} onClick={()=>save('sent')}><Send size={15}/>Send</Button></div></header>
 <div className="qw4-workflow">{workflow.map(([label,done],i)=><span key={String(label)} className={done?'done':''}><i>{done?'✓':i+1}</i>{label}</span>)}</div>
 <div className="qw4-layout"><main className="qw4-main"><section className="qw4-summary-line"><div><b>{customerName}</b><span>{route(origin,destination)}</span><small>{[mode,direction,serviceType,incoterm].filter(Boolean).join(' · ')}</small></div><button onClick={()=>setDetailsOpen(v=>!v)}>{detailsOpen?<ChevronDown/>:<ChevronRight/>}Edit details</button></section>
 {detailsOpen&&<section className="qw4-panel qw4-details"><div className="qw4-grid"><label>Customer<input value={customerName} onChange={e=>setCustomerName(e.target.value)}/></label><label>Email<input value={customerEmail} onChange={e=>setCustomerEmail(e.target.value)}/></label><label>Reference<input value={customerReference} onChange={e=>setCustomerReference(e.target.value)}/></label><label>Commodity<input value={commodity} onChange={e=>setCommodity(e.target.value)}/></label><label>Mode<input value={mode} onChange={e=>setMode(e.target.value)}/></label><label>Direction<input value={direction} onChange={e=>setDirection(e.target.value)}/></label><label>Origin<input value={origin} onChange={e=>setOrigin(e.target.value)}/></label><label>Destination<input value={destination} onChange={e=>setDestination(e.target.value)}/></label><label>Service<input value={serviceType} onChange={e=>setServiceType(e.target.value)}/></label><label>Incoterm<input value={incoterm} onChange={e=>setIncoterm(e.target.value)}/></label></div></section>}
 <section className="qw4-panel qw4-services-panel"><button className="qw4-section-toggle" onClick={()=>setServicesOpen(v=>!v)}><span><small>SERVICE LIBRARY</small><b>{services.length?`${services.length} selected`:'Add optional services'}</b></span>{servicesOpen?<ChevronDown/>:<ChevronRight/>}</button>{servicesOpen&&<><div className="qw5-library-toolbar"><button onClick={()=>{setEditingService({id:crypto.randomUUID(),name:'New service',icon:'+',chargeName:'New service',defaultSell:0,note:'Optional service'});setServiceEditorOpen(true)}}><Plus size={14}/>New service</button><button onClick={()=>setServiceEditorOpen(true)}><Pencil size={14}/>Manage library</button></div><div className="qw4-service-library">{serviceLibrary.map(s=><button key={s.id} className={services.includes(s.id)?'active':''} onClick={()=>toggleService(s)}><span className="qw4-service-icon">{s.icon}</span><span><b>{s.name}</b><small>{s.note}</small></span><em>{services.includes(s.id)?'Added':'Add'}</em></button>)}</div></>}</section>
 <section className="qw4-panel qw4-charges qw5-charges"><div className="qw4-section-head"><div><small>PRICING</small><h2>Charges</h2><p>{charges.length} lines · every field is editable</p></div><div><button onClick={()=>setCharges(v=>[...v,blankCharge()])}><Plus size={15}/>Add charge</button><button onClick={()=>setLibraryOpen(true)}><Library size={15}/>Charge library</button></div></div><div className="qw4-charge-table"><div className="qw4-charge-head"><span>Charge</span><span>Basis</span><span>Qty</span><span>Vendor</span><span>Sell</span><span>Total</span><span/></div><div className="qw4-charge-scroll">{charges.map(c=><div className={`qw4-charge-row ${c.source?.startsWith('service:')?'service-charge':''}`} key={c.id}><input value={c.description} onChange={e=>patchCharge(c.id,{description:e.target.value})}/><select value={c.basis} onChange={e=>patchCharge(c.id,{basis:e.target.value as Basis,autoQuantity:e.target.value!=='flat'})}>{Object.entries(basisLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input type="number" value={c.quantity} onChange={e=>patchCharge(c.id,{quantity:number(e.target.value),autoQuantity:false})}/><input type="number" value={c.rate} onChange={e=>patchCharge(c.id,{rate:number(e.target.value)})}/><input type="number" value={c.sellRate} onChange={e=>patchCharge(c.id,{sellRate:number(e.target.value)})}/><output><b>{money(c.sell,currency)}</b><small>{c.rate?(((c.sellRate/c.rate)-1)*100).toFixed(1):'0.0'}% margin</small></output><button onClick={()=>setCharges(v=>v.filter(x=>x.id!==c.id))}><Trash2 size={15}/></button></div>)}</div></div></section>
 <section className="qw4-panel"><button className="qw4-section-toggle" onClick={()=>setTermsOpen(v=>!v)}><span><small>COMMERCIAL</small><b>Validity, carrier and terms</b></span>{termsOpen?<ChevronDown/>:<ChevronRight/>}</button>{termsOpen&&<div className="qw4-grid qw4-commercial"><label>Currency<input value={currency} onChange={e=>setCurrency(e.target.value)}/></label><label>Valid until<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><label>Transit<input value={transit} onChange={e=>setTransit(e.target.value)}/></label><label>Carrier<input value={carrier} onChange={e=>setCarrier(e.target.value)}/></label><label>Frequency<input value={frequency} onChange={e=>setFrequency(e.target.value)}/></label><label>Routing<input value={routing} onChange={e=>setRouting(e.target.value)}/></label><label className="wide">Notes<textarea value={customerNotes} onChange={e=>setCustomerNotes(e.target.value)}/></label><label className="wide">Terms<textarea value={terms} onChange={e=>setTerms(e.target.value)}/></label></div>}</section>{message&&<div className="qw4-message">{message}</div>}</main>
 <aside className="qw4-inspector"><div className="qw4-total"><span>Customer sell</span><strong>{money(totals.sell,currency)}</strong></div><div className="qw4-money-grid"><span><small>Vendor cost</small><b>{money(totals.cost,currency)}</b></span><span><small>Profit</small><b>{money(totals.profit,currency)}</b></span><span><small>Margin</small><b>{totals.margin.toFixed(1)}%</b></span></div><Button variant="secondary" onClick={createPdf}><FileDown size={15}/>Create PDF</Button><Button onClick={()=>save('sent')}><Send size={15}/>Send quote</Button></aside></div>
 {libraryOpen&&<div className="qw5-modal"><section><header><div><small>CHARGE LIBRARY</small><h2>Saved charges</h2></div><button onClick={()=>setLibraryOpen(false)}><X/></button></header><button className="qw5-new" onClick={()=>setEditingCharge({id:'',name:'New charge',type:'flat',rate:0,qty:1,minimum:0})}><Plus/>New saved charge</button><div className="qw5-library-list">{chargeLibrary.map(item=><article key={item.id}><button onClick={()=>addFromLibrary(item)}><b>{item.name}</b><small>{basisLabels[normalizeBasis(item.type)]} · {money(item.rate,currency)}</small></button><button onClick={()=>setEditingCharge(item)}><Pencil/></button><button onClick={()=>deleteChargeLibrary(item.id)}><Trash2/></button></article>)}</div></section></div>}
 {editingCharge&&<div className="qw5-modal"><section className="qw5-editor"><header><h2>Edit charge library item</h2><button onClick={()=>setEditingCharge(null)}><X/></button></header><label>Name<input value={editingCharge.name} onChange={e=>setEditingCharge({...editingCharge,name:e.target.value})}/></label><label>Basis<select value={editingCharge.type} onChange={e=>setEditingCharge({...editingCharge,type:e.target.value})}>{Object.entries(basisLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Default rate<input type="number" value={editingCharge.rate} onChange={e=>setEditingCharge({...editingCharge,rate:number(e.target.value)})}/></label><label>Default quantity<input type="number" value={editingCharge.qty} onChange={e=>setEditingCharge({...editingCharge,qty:number(e.target.value)})}/></label><Button onClick={saveChargeLibrary}>Save library item</Button></section></div>}
 {serviceEditorOpen&&<div className="qw5-modal"><section><header><div><small>SERVICE LIBRARY</small><h2>Manage services</h2></div><button onClick={()=>{setServiceEditorOpen(false);setEditingService(null)}}><X/></button></header>{editingService?<div className="qw5-editor"><label>Service name<input value={editingService.name} onChange={e=>setEditingService({...editingService,name:e.target.value})}/></label><label>Description<input value={editingService.note} onChange={e=>setEditingService({...editingService,note:e.target.value})}/></label><label>Linked charge<input value={editingService.chargeName} onChange={e=>setEditingService({...editingService,chargeName:e.target.value})}/></label><label>Default sell<input type="number" value={editingService.defaultSell} onChange={e=>setEditingService({...editingService,defaultSell:number(e.target.value)})}/></label><Button onClick={saveService}>Save service</Button></div>:<div className="qw5-library-list">{serviceLibrary.map(s=><article key={s.id}><button onClick={()=>setEditingService(s)}><b>{s.name}</b><small>{s.chargeName} · {money(s.defaultSell,currency)}</small></button><button onClick={()=>setEditingService(s)}><Pencil/></button><button onClick={()=>deleteService(s.id)}><Trash2/></button></article>)}</div>}</section></div>}
 </div>
}