import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ChevronDown, ChevronRight, FileText, Library, Mail, Plus, Save, Send, Trash2 } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { Button, EmptyState } from './ui'

type Basis='flat'|'per_actual_kg'|'per_chargeable_kg'|'per_lb'|'per_cbm'|'per_piece'|'per_pallet'|'per_container'
type Cargo={id:string;quantity:number;packaging_type:string|null;commodity:string|null;weight_value:number|null;weight_unit:string|null;length_value:number|null;width_value:number|null;height_value:number|null;dimension_unit:string|null}
type Charge={id:string;description:string;basis:Basis;quantity:number;rate:number;sellRate:number;markup:number;minimum:number;cost:number;sell:number;autoQuantity:boolean;source?:string}
type QuoteRow={id:string;quote_number:string;customer_name:string|null;status:string;quote_data:any;quote_request_id:string|null;created_at:string}
type RequestRow={id:string;request_number:string;customer_company:string|null;contact_name:string|null;contact_email:string;contact_phone:string|null;customer_reference:string|null;mode:string|null;service_type:string|null;direction:string|null;origin_code:string|null;origin_name:string|null;destination_code:string|null;destination_name:string|null;incoterm:string|null;notes:string|null}
type SelectedRate={id:string;rfq_number:string;response_data:any;vendors?:{company?:string}|null}

const basisLabels:Record<Basis,string>={flat:'Flat',per_actual_kg:'Actual kg',per_chargeable_kg:'Chargeable kg',per_lb:'Lb',per_cbm:'CBM',per_piece:'Piece',per_pallet:'Pallet',per_container:'Container'}
const serviceOptions=['Pickup','Delivery','Customs Clearance','Cargo Insurance','Storage','Liftgate','Residential','Hazmat / DG','White Glove','Appointment','Export Documents','Import Documents','Bond','AES Filing','ISF']
const text=(v:any,f='')=>{if(v==null||v==='')return f;if(typeof v==='string'||typeof v==='number')return String(v);if(Array.isArray(v))return v.map(x=>text(x)).filter(Boolean).join(' · ');if(typeof v==='object'){for(const k of ['label','name','value','code','title','text']){const s=text(v[k]);if(s)return s}}return f}
const number=(v:any)=>Number(v)||0
const money=(n:number,currency='USD')=>{try{return new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:2}).format(Number.isFinite(n)?n:0)}catch{return `$${(Number(n)||0).toFixed(2)}`}}
const route=(origin:string,destination:string)=>`${origin||'Origin'} → ${destination||'Destination'}`
const normalizeBasis=(type:string):Basis=>({flat:'flat',per_chargeable_kg:'per_chargeable_kg',per_kg:'per_actual_kg',per_actual_kg:'per_actual_kg',per_lb:'per_lb',per_cbm:'per_cbm',per_piece:'per_piece',per_pallet:'per_pallet',per_container:'per_container',kg:'per_actual_kg',lb:'per_lb',cbm:'per_cbm',pallet:'per_pallet',container:'per_container',shipment:'flat'} as Record<string,Basis>)[type]||'flat'
const blankCharge=():Charge=>({id:crypto.randomUUID(),description:'New charge',basis:'flat',quantity:1,rate:0,sellRate:0,markup:0,minimum:0,cost:0,sell:0,autoQuantity:false})
function normalizeCargo(rows:any[]):Cargo[]{return(rows||[]).map((c:any)=>({id:c.id||crypto.randomUUID(),quantity:number(c.quantity??c.qty)||1,packaging_type:text(c.packaging_type??c.desc,'piece'),commodity:text(c.commodity??c.desc,'Cargo'),weight_value:number(c.weight_value??c.weight),weight_unit:text(c.weight_unit??c.wUnit,'kg'),length_value:number(c.length_value??c.l),width_value:number(c.width_value??c.w),height_value:number(c.height_value??c.h),dimension_unit:text(c.dimension_unit??c.dUnit,'cm')}))}
function cargoMetrics(cargo:Cargo[]){let actualKg=0,cbm=0,pieces=0,pallets=0,containers=0;for(const c of cargo){const qty=number(c.quantity);pieces+=qty;const w=number(c.weight_value);actualKg+=(text(c.weight_unit,'kg').toLowerCase()==='lb'?w*.453592:w)*qty;const f=text(c.dimension_unit,'cm').toLowerCase()==='in'?2.54:1;cbm+=number(c.length_value)*f*number(c.width_value)*f*number(c.height_value)*f/1e6*qty;const p=text(c.packaging_type).toLowerCase();if(p.includes('pallet'))pallets+=qty;if(p.includes('container'))containers+=qty}return{actualKg,chargeableKg:Math.max(actualKg,cbm*167),cbm,pieces,pallets,containers}}
const quantityFor=(basis:Basis,m:ReturnType<typeof cargoMetrics>)=>({flat:1,per_actual_kg:m.actualKg,per_chargeable_kg:m.chargeableKg,per_lb:m.actualKg*2.20462,per_cbm:m.cbm,per_piece:m.pieces,per_pallet:m.pallets,per_container:m.containers}[basis]||0)
function calculate(c:Charge,m:ReturnType<typeof cargoMetrics>):Charge{const quantity=c.autoQuantity?quantityFor(c.basis,m):number(c.quantity),rate=number(c.rate),sellRate=number(c.sellRate),cost=Math.max(quantity*rate,number(c.minimum)),sell=quantity*sellRate;return{...c,quantity,rate,sellRate,cost,sell,markup:rate?((sellRate/rate)-1)*100:number(c.markup)}}
function normalizeCharges(rows:any[],m:ReturnType<typeof cargoMetrics>):Charge[]{return(rows||[]).map((c:any)=>{const basis=normalizeBasis(text(c.basis??c.type??c.unit,'flat')),quantity=number(c.quantity??c.qty)||quantityFor(basis,m)||1,rate=number(c.rate)||(basis==='flat'?number(c.amount??c.cost):0),minimum=number(c.minimum??c.min),cost=number(c.cost??c.amount)||Math.max(quantity*rate,minimum),sell=number(c.sell??c.amount)||cost,sellRate=number(c.sellRate??c.sell_rate)||(quantity?sell/quantity:sell)||rate;return{id:c.id||crypto.randomUUID(),description:text(c.description??c.name,'Charge'),basis,quantity,rate,sellRate,markup:rate?((sellRate/rate)-1)*100:0,minimum,cost,sell:quantity*sellRate,autoQuantity:c.autoQuantity??basis!=='flat',source:c.source}})}

export function QuoteWorkspaceV4(){
 const[params,setParams]=useSearchParams();const quoteId=params.get('quote')
 if(!quoteId)return <div className="qw4-empty"><EmptyState icon={<FileText size={28}/>} title="No quote selected" copy="Choose a quote from the queue."/></div>
 return <QuoteWorkspaceV4Editor quoteId={quoteId} onClose={()=>setParams({})}/>
}

function QuoteWorkspaceV4Editor({quoteId,onClose}:{quoteId:string;onClose:()=>void}){
 const[quote,setQuote]=useState<QuoteRow|null>(null),[request,setRequest]=useState<RequestRow|null>(null),[selectedRate,setSelectedRate]=useState<SelectedRate|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const[cargo,setCargo]=useState<Cargo[]>([]),[charges,setCharges]=useState<Charge[]>([]),[services,setServices]=useState<string[]>([]),[detailsOpen,setDetailsOpen]=useState(false),[servicesOpen,setServicesOpen]=useState(true),[termsOpen,setTermsOpen]=useState(false)
 const[customerName,setCustomerName]=useState(''),[customerEmail,setCustomerEmail]=useState(''),[customerReference,setCustomerReference]=useState(''),[commodity,setCommodity]=useState(''),[mode,setMode]=useState(''),[direction,setDirection]=useState(''),[serviceType,setServiceType]=useState(''),[incoterm,setIncoterm]=useState(''),[origin,setOrigin]=useState(''),[destination,setDestination]=useState('')
 const[currency,setCurrency]=useState('USD'),[validUntil,setValidUntil]=useState(''),[transit,setTransit]=useState(''),[carrier,setCarrier]=useState(''),[routing,setRouting]=useState(''),[frequency,setFrequency]=useState(''),[customerNotes,setCustomerNotes]=useState(''),[terms,setTerms]=useState('Rates subject to space and equipment availability. Duties, taxes, inspections, storage, demurrage and detention are excluded unless specifically stated.')
 const metrics=useMemo(()=>cargoMetrics(cargo),[cargo])
 const totals=useMemo(()=>{const cost=charges.reduce((s,c)=>s+number(c.cost),0),sell=charges.reduce((s,c)=>s+number(c.sell),0),profit=sell-cost;return{cost,sell,profit,margin:sell?profit/sell*100:0}},[charges])
 const generated=Boolean(quote?.quote_request_id)
 useEffect(()=>{(async()=>{setLoading(true);const{data:q,error}=await supabase.from('quotes').select('*').eq('id',quoteId).single();if(error||!q){setMessage(error?.message||'Quote not found');setLoading(false);return}const qr=q as QuoteRow,d=qr.quote_data&&typeof qr.quote_data==='object'?qr.quote_data:{};setQuote(qr);let req:RequestRow|null=null,rfq:SelectedRate|null=null,cargoRows=normalizeCargo(d.cargo||[]);if(qr.quote_request_id){const[{data:r},{data:cg},{data:sr}]=await Promise.all([supabase.from('quote_requests').select('*').eq('id',qr.quote_request_id).maybeSingle(),supabase.from('quote_request_cargo').select('*').eq('quote_request_id',qr.quote_request_id).order('line_number'),supabase.from('vendor_rfqs').select('id,rfq_number,response_data,vendors(company)').eq('quote_request_id',qr.quote_request_id).eq('status','selected').order('selected_at',{ascending:false}).limit(1).maybeSingle()]);req=(r||null) as RequestRow|null;rfq=(sr||null) as SelectedRate|null;if((cg||[]).length)cargoRows=normalizeCargo(cg||[])}setRequest(req);setSelectedRate(rfq);setCargo(cargoRows);const m=cargoMetrics(cargoRows),response=rfq?.response_data||d.vendor?.response||{};setCustomerName(text(qr.customer_name,req?.customer_company||req?.contact_name||'Customer'));setCustomerEmail(text(d.customerEmail,req?.contact_email||''));setCustomerReference(text(d.customerReference,req?.customer_reference||''));setCommodity(text(d.commodity,cargoRows.map(c=>c.commodity).filter(Boolean).join(', ')));setMode(text(d.mode,req?.mode||''));setDirection(text(d.direction,req?.direction||''));setServiceType(text(d.serviceType,req?.service_type||''));setIncoterm(text(d.incoterm,req?.incoterm||''));setOrigin(text(d.origin,req?.origin_code||req?.origin_name||''));setDestination(text(d.destination,req?.destination_code||req?.destination_name||''));setCurrency(text(d.currency,response.currency||'USD'));setValidUntil(text(d.validUntil,response.validUntil||response.valid_until||''));setTransit(text(d.transit,response.transit||''));setCarrier(text(d.carrier,response.carrier||d.vendor?.name||rfq?.vendors?.company||''));setRouting(text(d.routing,response.routing||''));setFrequency(text(d.frequency,response.frequency||''));setCustomerNotes(text(d.customerNotes));setTerms(text(d.terms,terms));setServices(Array.isArray(d.services)?d.services:[]);setCharges(normalizeCharges(d.charges||response.charges||[],m).map(c=>calculate(c,m)));setDetailsOpen(!qr.quote_request_id);setLoading(false)})()},[quoteId])
 useEffect(()=>setCharges(rows=>rows.map(c=>calculate(c,metrics))),[metrics.actualKg,metrics.cbm,metrics.pieces,metrics.pallets,metrics.containers])
 const patchCharge=(id:string,patch:Partial<Charge>)=>setCharges(rows=>rows.map(c=>c.id===id?calculate({...c,...patch},metrics):c))
 const toggleService=(service:string)=>setServices(current=>current.includes(service)?current.filter(x=>x!==service):[...current,service])
 const buildData=()=>({...quote?.quote_data,customerEmail,customerReference,commodity,mode,direction,serviceType,incoterm,origin,destination,route:route(origin,destination),currency,validUntil,transit,carrier,routing,frequency,customerNotes,terms,cargo,metrics,charges,services,totals,vendor:{...quote?.quote_data?.vendor,rfqId:selectedRate?.id||quote?.quote_data?.vendor?.rfqId,name:selectedRate?.vendors?.company||quote?.quote_data?.vendor?.name,response:selectedRate?.response_data||quote?.quote_data?.vendor?.response}})
 const save=async(status=quote?.status||'draft')=>{if(!quote)return;setSaving(true);setMessage('');const{data,error}=await supabase.from('quotes').update({customer_name:customerName,status,quote_data:buildData()}).eq('id',quote.id).select('*').single();setSaving(false);if(error){setMessage(error.message);return}setQuote(data as QuoteRow);setMessage(status==='sent'?'Quote marked sent.':'Quote saved.')}
 if(loading)return <div className="qw4-loading">Loading quote…</div>
 const workflow=[['Request',generated],['RFQs',Boolean(selectedRate||quote?.quote_data?.vendor)],['Vendor',Boolean(selectedRate||quote?.quote_data?.vendor?.name)],['Review',true],['Sent',quote?.status==='sent']]
 return <div className="qw4-shell">
  <header className="qw4-topbar"><button onClick={onClose}><ArrowLeft size={16}/>Quotes</button><div><small>{generated?'AUTOMATED QUOTE':'MANUAL QUOTE'}</small><h1>{quote?.quote_number||'Quote'}</h1><p>{customerName} · {route(origin,destination)}</p></div><div className="qw4-actions"><Button variant="secondary" disabled={saving} onClick={()=>save()}><Save size={15}/>Save</Button><Button variant="secondary" onClick={()=>window.dispatchEvent(new CustomEvent('open-quote-preview'))}>Preview</Button><Button variant="secondary" onClick={()=>window.location.href=`mailto:${customerEmail}`}><Mail size={15}/>Email</Button><Button disabled={saving} onClick={()=>save('sent')}><Send size={15}/>Send</Button></div></header>
  <div className="qw4-workflow">{workflow.map(([label,done],index)=><span key={String(label)} className={done?'done':''}><i>{done?'✓':index+1}</i>{label}</span>)}</div>
  <div className="qw4-layout">
   <main className="qw4-main">
    <section className="qw4-summary-line"><div><b>{customerName||'Customer'}</b><span>{route(origin,destination)}</span><small>{[mode,direction,serviceType,incoterm].filter(Boolean).join(' · ')}</small></div><button onClick={()=>setDetailsOpen(v=>!v)}>{detailsOpen?<ChevronDown size={16}/>:<ChevronRight size={16}/>}Edit details</button></section>
    {detailsOpen&&<section className="qw4-panel qw4-details"><div className="qw4-grid"><label>Customer<input value={customerName} onChange={e=>setCustomerName(e.target.value)}/></label><label>Email<input value={customerEmail} onChange={e=>setCustomerEmail(e.target.value)}/></label><label>Reference<input value={customerReference} onChange={e=>setCustomerReference(e.target.value)}/></label><label>Commodity<input value={commodity} onChange={e=>setCommodity(e.target.value)}/></label><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="">Select</option><option value="air">Air</option><option value="ocean">Ocean</option><option value="ground">Ground</option></select></label><label>Direction<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="">Select</option><option value="import">Import</option><option value="export">Export</option><option value="domestic">Domestic</option></select></label><label>Origin<input value={origin} onChange={e=>setOrigin(e.target.value)}/></label><label>Destination<input value={destination} onChange={e=>setDestination(e.target.value)}/></label><label>Service<input value={serviceType} onChange={e=>setServiceType(e.target.value)}/></label><label>Incoterm<input value={incoterm} onChange={e=>setIncoterm(e.target.value)}/></label></div><div className="qw4-metrics"><span><b>{metrics.pieces}</b>Pieces</span><span><b>{metrics.actualKg.toFixed(1)} kg</b>Actual</span><span><b>{metrics.chargeableKg.toFixed(1)} kg</b>Chargeable</span><span><b>{metrics.cbm.toFixed(3)}</b>CBM</span></div></section>}
    <section className="qw4-panel"><button className="qw4-section-toggle" onClick={()=>setServicesOpen(v=>!v)}><span><small>SERVICES</small><b>{services.length?`${services.length} selected`:'No services selected'}</b></span>{servicesOpen?<ChevronDown/>:<ChevronRight/>}</button>{servicesOpen&&<div className="qw4-services">{serviceOptions.map(service=><button key={service} className={services.includes(service)?'active':''} onClick={()=>toggleService(service)}>{services.includes(service)?'✓ ':''}{service}</button>)}</div>}</section>
    <section className="qw4-panel qw4-charges"><div className="qw4-section-head"><div><small>PRICING</small><h2>Charges</h2><p>{charges.length} lines · {generated?'prefilled from selected vendor and rules':'manual quote'}</p></div><div><button onClick={()=>setCharges(v=>[...v,blankCharge()])}><Plus size={15}/>Add charge</button><button><Library size={15}/>Library</button></div></div><div className="qw4-charge-head"><span>Charge</span><span>Basis</span><span>Qty</span><span>Vendor</span><span>Sell</span><span>Total</span><span/></div>{charges.map(c=><div className="qw4-charge-row" key={c.id}><input value={c.description} onChange={e=>patchCharge(c.id,{description:e.target.value})}/><select value={c.basis} onChange={e=>patchCharge(c.id,{basis:e.target.value as Basis,autoQuantity:e.target.value!=='flat'})}>{Object.entries(basisLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input type="number" value={c.quantity} onChange={e=>patchCharge(c.id,{quantity:number(e.target.value),autoQuantity:false})}/><input type="number" value={c.rate} onChange={e=>patchCharge(c.id,{rate:number(e.target.value)})}/><input type="number" value={c.sellRate} onChange={e=>patchCharge(c.id,{sellRate:number(e.target.value)})}/><output><b>{money(c.sell,currency)}</b><small>{c.markup.toFixed(1)}% margin</small></output><button onClick={()=>setCharges(rows=>rows.filter(x=>x.id!==c.id))}><Trash2 size={15}/></button></div>)}</section>
    <section className="qw4-panel"><button className="qw4-section-toggle" onClick={()=>setTermsOpen(v=>!v)}><span><small>COMMERCIAL</small><b>Validity, carrier and terms</b></span>{termsOpen?<ChevronDown/>:<ChevronRight/>}</button>{termsOpen&&<div className="qw4-grid qw4-commercial"><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD</option><option>EUR</option><option>GBP</option></select></label><label>Valid until<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><label>Transit<input value={transit} onChange={e=>setTransit(e.target.value)}/></label><label>Carrier<input value={carrier} onChange={e=>setCarrier(e.target.value)}/></label><label>Frequency<input value={frequency} onChange={e=>setFrequency(e.target.value)}/></label><label>Routing<input value={routing} onChange={e=>setRouting(e.target.value)}/></label><label className="wide">Customer notes<textarea value={customerNotes} onChange={e=>setCustomerNotes(e.target.value)}/></label><label className="wide">Terms<textarea value={terms} onChange={e=>setTerms(e.target.value)}/></label></div>}</section>{message&&<div className="qw4-message">{message}</div>}
   </main>
   <aside className="qw4-inspector"><div className="qw4-status"><small>{quote?.status||'draft'}</small><b>{generated?'Ready to review':'Build quote'}</b></div><div className="qw4-total"><span>Customer sell</span><strong>{money(totals.sell,currency)}</strong></div><div className="qw4-money-grid"><span><small>Vendor cost</small><b>{money(totals.cost,currency)}</b></span><span><small>Profit</small><b>{money(totals.profit,currency)}</b></span><span><small>Margin</small><b>{totals.margin.toFixed(1)}%</b></span></div><dl><div><dt>Vendor</dt><dd>{selectedRate?.vendors?.company||quote?.quote_data?.vendor?.name||'Not selected'}</dd></div><div><dt>Transit</dt><dd>{transit||'To be confirmed'}</dd></div><div><dt>Valid until</dt><dd>{validUntil||'To be confirmed'}</dd></div><div><dt>Services</dt><dd>{services.length||'None'}</dd></div></dl><div className="qw4-review"><h3>Review</h3><p>✓ Shipment data available</p><p>✓ Charges calculated</p><p>{selectedRate||quote?.quote_data?.vendor?.name?'✓':'!'} Vendor selected</p><p>{totals.margin>=15?'✓':'!'} Margin {totals.margin>=15?'acceptable':'needs review'}</p></div><Button variant="secondary">Preview</Button><Button onClick={()=>save('sent')}><Send size={15}/>Send quote</Button></aside>
  </div>
 </div>
}
