import { Archive, Box, Check, Clock3, FileText, MoreHorizontal, Plane, Ship, Target, Trash2, Truck, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { Button, StatusBadge } from './ui'
import { RfqComposer } from './RfqComposer'
import { ResponsiveVendorRateWorkspace } from './ResponsiveVendorRateWorkspace'

export type RequestSummary={id:string;request_number:string;customer_company:string|null;contact_name:string|null;contact_email:string;contact_phone?:string|null;mode:string|null;service_type:string|null;origin_code:string|null;origin_name:string|null;destination_code:string|null;destination_name:string|null;status:string;submitted_at:string;notes?:string|null;customer_reference?:string|null;target_rate_amount?:number|null;target_rate_currency?:string|null;target_rate_basis?:string|null;archived_at?:string|null}
type Cargo={id:string;quantity:number;packaging_type:string|null;commodity:string|null;weight_value:number|null;weight_unit:string|null;length_value:number|null;width_value:number|null;height_value:number|null;dimension_unit:string|null;stackable:boolean|null;dangerous_goods:boolean|null}
type Stop={id:string;stop_type:string;company:string|null;address_line1:string|null;city:string|null;state_region:string|null;postal_code:string|null;country:string|null;contact_name:string|null;phone:string|null;hours:string|null}
type Activity={id:string;title:string;description:string|null;created_at:string}
type Rfq={id:string;rfq_number:string;status:string;sent_to:string|null;selected_at:string|null;response_data:Record<string,unknown>|null;vendors?:{company?:string}|null}
type Quote={id:string;quote_number:string}
type ServiceLeg={id:string;sequence_no:number;service_type:string;service_label:string|null;origin_text:string|null;destination_text:string|null;details:Record<string,unknown>}
type DocumentRow={id:string;file_name:string;file_type:string|null;file_size:number|null;storage_path:string|null;created_at:string}
type WorkspaceTab='summary'|'cargo'|'rates'|'activity'

const modeIcon=(mode:string|null)=>mode==='air'?<Plane size={18}/>:mode==='ocean'?<Ship size={18}/>:<Truck size={18}/>
const route=(r:RequestSummary)=>`${r.origin_code||r.origin_name||'—'} → ${r.destination_code||r.destination_name||'—'}`
const ageLabel=(value:string)=>{const diff=Math.max(0,Date.now()-new Date(value).getTime()),mins=Math.floor(diff/60000);if(mins<1)return'Received just now';if(mins<60)return`Received ${mins}m ago`;const hours=Math.floor(mins/60);if(hours<24)return`Received ${hours}h ago`;const days=Math.floor(hours/24);return`Received ${days}d ago`}
const kgValue=(line:Cargo)=>{const weight=Number(line.weight_value)||0;return String(line.weight_unit||'kg').toLowerCase()==='lb'?weight*.453592:weight}
const responseSummary=(rfq:Rfq)=>{const raw=(rfq.response_data||{}) as any;const charges=Array.isArray(raw.charges)?raw.charges:[];const total=Number(raw.total)||charges.reduce((sum:number,c:any)=>sum+(Number(c.amount)||Number(c.cost)||0),0);return{total,currency:String(raw.currency||'USD'),carrier:String(raw.carrier||''),transit:String(raw.transit||''),validUntil:String(raw.validUntil||raw.valid_until||''),routing:String(raw.routing||''),frequency:String(raw.frequency||'')}}

export function RequestWorkspace({request,onClose,onChanged}:{request:RequestSummary|null;onClose:()=>void;onChanged:()=>void}){
 const[loading,setLoading]=useState(false),[cargo,setCargo]=useState<Cargo[]>([]),[stops,setStops]=useState<Stop[]>([]),[activities,setActivities]=useState<Activity[]>([]),[rfqs,setRfqs]=useState<Rfq[]>([]),[quote,setQuote]=useState<Quote|null>(null),[legs,setLegs]=useState<ServiceLeg[]>([]),[documents,setDocuments]=useState<DocumentRow[]>([]),[rfqOpen,setRfqOpen]=useState(false),[ratesOpen,setRatesOpen]=useState(false),[menu,setMenu]=useState(false),[busy,setBusy]=useState(false),[tab,setTab]=useState<WorkspaceTab>('summary')
 const metrics=useMemo(()=>{let pieces=0,weightKg=0,cbm=0;for(const line of cargo){const qty=Number(line.quantity)||1,factor=String(line.dimension_unit||'cm').toLowerCase()==='in'?2.54:1;pieces+=qty;weightKg+=kgValue(line)*qty;cbm+=(Number(line.length_value)||0)*factor*(Number(line.width_value)||0)*factor*(Number(line.height_value)||0)*factor/1e6*qty}return{pieces,weightKg,cbm}},[cargo])
 const load=()=>{if(!request)return;setLoading(true);Promise.all([supabase.from('quote_request_cargo').select('*').eq('quote_request_id',request.id).order('line_number'),supabase.from('quote_request_stops').select('*').eq('quote_request_id',request.id).order('created_at'),supabase.from('commercial_activities').select('*').eq('quote_request_id',request.id).order('created_at',{ascending:false}),supabase.from('vendor_rfqs').select('id,rfq_number,status,sent_to,selected_at,response_data,vendors(company)').eq('quote_request_id',request.id).order('created_at',{ascending:false}),supabase.from('quotes').select('id,quote_number').eq('quote_request_id',request.id).order('version_number',{ascending:false}).limit(1).maybeSingle(),supabase.from('quote_request_services').select('*').eq('quote_request_id',request.id).order('sequence_no'),supabase.from('quote_request_documents').select('*').eq('quote_request_id',request.id).order('created_at',{ascending:false})]).then(([c,s,a,r,q,l,d])=>{setCargo((c.data||[]) as Cargo[]);setStops((s.data||[]) as Stop[]);setActivities((a.data||[]) as Activity[]);setRfqs((r.data||[]) as unknown as Rfq[]);setQuote((q.data||null) as Quote|null);setLegs((l.data||[]) as ServiceLeg[]);setDocuments((d.data||[]) as DocumentRow[])}).catch(()=>{}).finally(()=>setLoading(false))}
 useEffect(()=>{setTab('summary');setMenu(false);setCargo([]);setStops([]);setActivities([]);setRfqs([]);setQuote(null);setLegs([]);setDocuments([]);load()},[request?.id])
 if(!request)return null
 const openDocument=async(doc:DocumentRow)=>{if(!doc.storage_path)return;const{data}=await supabase.storage.from('quote-request-documents').createSignedUrl(doc.storage_path,120);if(data?.signedUrl)window.open(data.signedUrl,'_blank')}
 const archive=async()=>{if(!confirm(`Archive ${request.request_number}?`))return;setBusy(true);await supabase.from('quote_requests').update({archived_at:new Date().toISOString()}).eq('id',request.id);setBusy(false);onChanged();onClose()}
 const remove=async()=>{if(!confirm(`Permanently delete ${request.request_number}? This cannot be undone.`))return;if(!confirm('Delete the request and all connected cargo, documents, services, RFQs and activity?'))return;setBusy(true);const paths=documents.map(d=>d.storage_path).filter(Boolean) as string[];if(paths.length)await supabase.storage.from('quote-request-documents').remove(paths);const{error}=await supabase.from('quote_requests').delete().eq('id',request.id);setBusy(false);if(error){alert(error.message);return}onChanged();onClose()}
 const openQuote=()=>{onClose();location.hash=quote?`#/quotes?quote=${quote.id}`:`#/quotes?request=${request.id}`}
 const responded=rfqs.filter(r=>['responded','received','selected','accepted'].includes(String(r.status).toLowerCase()))
 const pending=rfqs.filter(r=>!responded.includes(r))
 const decision=responded.length?{tone:'ready',title:'Vendor rates ready',copy:`${responded.length} response${responded.length===1?'':'s'} available to compare.`,action:'Compare rates'}:rfqs.length?{tone:'pending',title:'Waiting on vendor rates',copy:`${pending.length||rfqs.length} RFQ${(pending.length||rfqs.length)===1?'':'s'} still require attention.`,action:'Open rates'}:{tone:'required',title:'Vendor pricing required',copy:'No vendor RFQ has been created for this shipment.',action:'Request vendor rates'}
 const primaryAction=()=>responded.length||rfqs.length?setRatesOpen(true):setRfqOpen(true)
 const selectVendor=async(r:Rfq)=>{const summary=responseSummary(r);if(!summary.total){setRatesOpen(true);return}if(!confirm(`Select ${r.vendors?.company||'this vendor'} for ${summary.currency} ${summary.total.toFixed(2)}?`))return;setBusy(true);await supabase.from('vendor_rfqs').update({selected_at:null,status:'responded'}).eq('quote_request_id',request.id).neq('id',r.id);const{error}=await supabase.from('vendor_rfqs').update({selected_at:new Date().toISOString(),status:'selected'}).eq('id',r.id);setBusy(false);if(error){alert(error.message);return}load();onChanged()}

 return <><div className="request-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="request-drawer pricing-decision-workspace">
  <header className="drawer-head compact-request-head"><div className="drawer-title"><span className="mode-mark">{modeIcon(request.mode)}</span><div><small>{request.request_number}</small><h2>{route(request)}</h2><p>{request.customer_company||request.contact_name||'Guest request'} · {request.mode||'Freight'} {request.service_type||''}</p></div></div><div className="drawer-head-actions"><button className="drawer-close" onClick={()=>setMenu(!menu)}><MoreHorizontal size={20}/></button><button className="drawer-close" onClick={onClose}><X size={20}/></button>{menu&&<div className="request-menu"><button disabled={busy} onClick={archive}><Archive size={15}/>Archive request</button><button className="danger" disabled={busy} onClick={remove}><Trash2 size={15}/>Delete permanently</button></div>}</div></header>
  <div className="request-quick-meta"><StatusBadge status={request.status}/><span className="request-age"><Clock3 size={14}/>{ageLabel(request.submitted_at)}</span><span>{new Date(request.submitted_at).toLocaleString()}</span></div>
  <nav className="decision-tabs">{(['summary','cargo','rates','activity'] as WorkspaceTab[]).map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item==='rates'?'Rates':item[0].toUpperCase()+item.slice(1)}</button>)}</nav>
  <div className="drawer-body decision-body">{loading?<div className="drawer-loading">Loading request workspace…</div>:<>
   {tab==='summary'&&<><section className={`pricing-decision-card tone-${decision.tone}`}><div><small>PRICING DECISION</small><h3>{decision.title}</h3><p>{decision.copy}</p></div><button onClick={primaryAction}>{decision.action}</button></section><section className="compact-shipment-facts"><article><span>Customer</span><b>{request.customer_company||request.contact_name||'Guest request'}</b><small>{request.contact_email}</small></article><article><span>Shipment</span><b>{route(request)}</b><small>{request.mode||'Freight'} · {request.service_type||'Service pending'}</small></article><article><span>Cargo</span><b>{metrics.pieces||cargo.length||0} pieces · {metrics.weightKg.toFixed(1)} kg</b><small>{metrics.cbm.toFixed(3)} CBM</small></article><article><span>Target</span><b>{request.target_rate_amount?`${request.target_rate_currency||'USD'} ${request.target_rate_amount.toLocaleString()}`:'Open to best rate'}</b><small>{request.target_rate_basis?.replaceAll('_',' ')||'No target supplied'}</small></article></section><section className="workflow-snapshot"><header><div><small>VENDOR PRICING</small><h3>{rfqs.length?`${rfqs.length} RFQ${rfqs.length===1?'':'s'}`:'No RFQs yet'}</h3></div><button onClick={()=>setTab('rates')}>View rates</button></header><div className="workflow-status-row"><span><i className="ready"/>{responded.length} responded</span><span><i className="pending"/>{pending.length} pending</span><span><i/>{quote?'Quote created':'Quote not created'}</span></div></section>{(request.customer_reference||request.notes||legs.length||stops.length||documents.length>0)&&<section className="request-supporting-info"><div className="section-label">ADDITIONAL DETAILS</div>{request.customer_reference&&<article><span>Reference</span><b>{request.customer_reference}</b></article>}{request.notes&&<article><span>Instructions</span><b>{request.notes}</b></article>}{legs.length>0&&<article><span>Service journey</span><b>{legs.map(l=>l.service_label||l.service_type.replaceAll('_',' ')).join(' · ')}</b></article>}{stops.length>0&&<article><span>Locations</span><b>{stops.length} additional stop{stops.length===1?'':'s'}</b></article>}{documents.length>0&&<article><span>Documents</span><b>{documents.length} uploaded</b></article>}</section>}</>}
   {tab==='cargo'&&<section className="workspace-section"><div className="section-label">CARGO SUMMARY</div><div className="cargo-metric-strip"><span><b>{metrics.pieces}</b><small>Pieces</small></span><span><b>{metrics.weightKg.toFixed(1)}</b><small>KG</small></span><span><b>{metrics.cbm.toFixed(3)}</b><small>CBM</small></span></div>{cargo.length?<div className="cargo-grid">{cargo.map(line=><article className="cargo-card" key={line.id}><div className="cargo-icon"><Box size={19}/></div><div><b>{line.quantity||1} {line.packaging_type||'piece(s)'}</b><p>{line.commodity||'Cargo'}</p><small>{line.weight_value||0} {line.weight_unit||'kg'} · {line.length_value||0}×{line.width_value||0}×{line.height_value||0} {line.dimension_unit||'cm'}</small></div></article>)}</div>:<div className="soft-empty"><Box size={20}/>No cargo lines found.</div>}</section>}
   {tab==='rates'&&<section className="workspace-section rates-workspace"><div className="rates-heading"><div><div className="section-label">VENDOR RATES</div><h3>{decision.title}</h3><p>Select quickly, edit a response, or compare all vendors.</p></div><button className="rates-primary" onClick={()=>setRatesOpen(true)}>Compare all</button></div>{rfqs.length?<div className="rfq-decision-list">{rfqs.map(r=>{const summary=responseSummary(r),hasResponse=summary.total>0||Boolean(r.response_data);return <article className={`rfq-decision-card ${r.selected_at?'selected':''}`} key={r.id}><header><div><b>{r.vendors?.company||'Vendor'}</b><small>{r.rfq_number}</small></div><StatusBadge status={r.status}/></header><div className="rfq-rate-summary"><span><small>Total</small><b>{summary.total?`${summary.currency} ${summary.total.toFixed(2)}`:'No rate yet'}</b></span><span><small>Carrier</small><b>{summary.carrier||'Pending'}</b></span><span><small>Transit</small><b>{summary.transit||'Pending'}</b></span><span><small>Valid until</small><b>{summary.validUntil||'Pending'}</b></span></div>{(summary.routing||summary.frequency)&&<p>{[summary.routing,summary.frequency].filter(Boolean).join(' · ')}</p>}<footer><button onClick={()=>setRatesOpen(true)}>{hasResponse?'Edit response':'Add response'}</button><button className="select-rate" disabled={busy||!summary.total||Boolean(r.selected_at)} onClick={()=>selectVendor(r)}>{r.selected_at?<><Check size={15}/>Selected</>:<><Check size={15}/>Select vendor</>}</button></footer></article>})}</div>:<div className="soft-empty"><Target size={20}/>Create a vendor RFQ to obtain lane pricing.</div>}<button className="secondary-rate-action" onClick={()=>setRfqOpen(true)}>Request another vendor rate</button></section>}
   {tab==='activity'&&<><section className="workspace-section"><div className="section-label">DOCUMENTS</div>{documents.length?<div className="document-grid">{documents.map(doc=><button key={doc.id} onClick={()=>openDocument(doc)}><FileText size={18}/><span><b>{doc.file_name}</b><small>{doc.file_size?`${(doc.file_size/1024/1024).toFixed(2)} MB`:doc.file_type||'Document'}</small></span></button>)}</div>:<div className="soft-empty"><FileText size={20}/>No documents uploaded.</div>}</section><section className="workspace-section"><div className="section-label">ACTIVITY TIMELINE</div><div className="timeline">{activities.length?activities.map(a=><article key={a.id}><i/><div><b>{a.title}</b><p>{a.description||''}</p><small>{new Date(a.created_at).toLocaleString()}</small></div></article>):<div className="soft-empty"><Clock3 size={20}/>No activity recorded yet.</div>}</div></section></>}
  </>}</div>
  <footer className="drawer-actions decision-actions"><Button variant="secondary" onClick={()=>setRfqOpen(true)}>Request vendor RFQ</Button>{rfqs.length>0&&<Button variant="secondary" onClick={()=>setRatesOpen(true)}>Compare rates</Button>}<Button onClick={openQuote}>{quote?`Open ${quote.quote_number}`:'Create quote'}</Button></footer>
 </aside></div>{rfqOpen&&<RfqComposer request={request} onClose={()=>setRfqOpen(false)} onCreated={()=>{load();onChanged();setTab('rates')}} onOpenRates={()=>{setRfqOpen(false);setRatesOpen(true)}}/>}{ratesOpen&&<ResponsiveVendorRateWorkspace request={request} onClose={()=>setRatesOpen(false)} onChanged={()=>{load();onChanged();setTab('rates')}}/>}</>
}