import { useEffect, useMemo, useRef, useState } from 'react'
import { Check, ChevronLeft, Copy, MoreHorizontal, Pencil, Plus, Save, Search, Send, Star, Trash2, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { getResendConnectionStatus, sendRfqEmails } from '../lib/resendRfq'
import { Button, StatusBadge } from './ui'
import type { RequestSummary } from './RequestWorkspace'

export type RfqWorkspaceMode = 'new-rfq-vendors' | 'new-rfq-template' | 'vendor-chat'
type Contact={id:string;name:string|null;email:string|null;is_primary:boolean|null}
type Vendor={id:string;company:string;preferred:boolean|null;modes:string[]|null;general_email:string|null;vendor_contacts?:Contact[]}
type ExistingRfq={id:string;rfq_number:string;status:string;sent_to:string|null;subject:string|null;message_body:string|null;sent_at:string|null;response_data:Record<string,unknown>|null;vendors?:{company?:string}|null}
type Message={id:string;direction:'outbound'|'inbound';sender_email:string|null;recipient_email:string|null;subject:string|null;body_text:string|null;status:string;sent_at:string|null;received_at:string|null;created_at:string;attachments:unknown[]}
type Template={id:string;name:string;subject_template:string;body_template:string;is_default:boolean;active?:boolean}
type EditorTarget='subject'|'body'

const requestRoute=(request:RequestSummary)=>`${request.origin_code||request.origin_name||'Origin'} → ${request.destination_code||request.destination_name||'Destination'}`
const rfqNumber=()=>`RFQ-${new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,12)}-${crypto.randomUUID().slice(0,4).toUpperCase()}`
const contact=(vendor:Vendor)=>vendor.vendor_contacts?.find(item=>item.is_primary&&item.email)||vendor.vendor_contacts?.find(item=>item.email)
const timestamp=(value:string|null)=>value?new Date(value).toLocaleString():'Pending'
const stripQuotedHistory=(value:string)=>{const lines=value.split('\n');const cutoff=lines.findIndex(line=>/^\s*>/.test(line)||/^\s*On .+wrote:\s*$/i.test(line)||/^\s*-{2,}\s*Original Message/i.test(line));return cutoff>0?lines.slice(0,cutoff).join('\n').trim():value}
const firstValue=(...values:unknown[])=>values.find(value=>value!==null&&value!==undefined&&String(value).trim()!=='')

const tokenDefinitions=[
 ['Customer name','{{customer_name}}'],['Customer reference','{{customer_reference}}'],['Request number','{{request_number}}'],
 ['Origin','{{origin}}'],['Destination','{{destination}}'],['Route','{{route}}'],['Mode','{{mode}}'],['Service level','{{service_level}}'],
 ['Cargo summary','{{cargo_summary}}'],['Pieces','{{pieces}}'],['Weight','{{weight}}'],['Volume','{{volume}}'],['Commodity','{{commodity}}'],
 ['Estimated departure','{{estimated_departure}}'],['Incoterm','{{incoterm}}'],['Special instructions','{{special_instructions}}']
] as const

const tokenValues=(request:RequestSummary):Record<string,string>=>{
 const raw=request as unknown as Record<string,unknown>
 const pieces=firstValue(raw.total_pieces,raw.pieces,0),weight=firstValue(raw.total_weight_kg,raw.weight_kg,0),volume=firstValue(raw.total_volume_cbm,raw.volume_cbm,0)
 return{
  customer_name:String(firstValue(request.customer_company,request.contact_name,'Customer')),
  customer_reference:String(firstValue(request.customer_reference,raw.reference,'Not provided')),
  request_number:request.request_number,
  origin:String(firstValue(request.origin_code,request.origin_name,'Origin')),
  destination:String(firstValue(request.destination_code,request.destination_name,'Destination')),
  route:requestRoute(request),
  mode:String(firstValue(request.mode,'Not specified')),
  service_level:String(firstValue(raw.service_level,raw.service,request.service_type,'Not specified')),
  cargo_summary:`${Number(pieces)} pieces · ${Number(weight)} kg · ${Number(volume)} CBM`,
  pieces:String(pieces),weight:`${Number(weight)} kg`,volume:`${Number(volume)} CBM`,
  commodity:String(firstValue(raw.commodity,'Not specified')),
  estimated_departure:String(firstValue(raw.estimated_departure,raw.requested_departure,'Not specified')),
  incoterm:String(firstValue(raw.incoterm,'Not specified')),
  special_instructions:String(firstValue(raw.special_instructions,raw.instructions,request.notes,'None')),
 }
}

const renderTemplate=(value:string,request:RequestSummary)=>{const values=tokenValues(request);return Object.entries(values).reduce((output,[key,replacement])=>output.replaceAll(`{{${key}}}`,replacement),value)}

export function RfqComposer({request,mode,rfqId,onModeChange,onClose,onCreated}:{request:RequestSummary;mode:RfqWorkspaceMode;rfqId:string|null;onModeChange:(mode:RfqWorkspaceMode,rfqId?:string)=>void;onClose:()=>void;onCreated:()=>void}){
 const[vendors,setVendors]=useState<Vendor[]>([]),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[rfqs,setRfqs]=useState<ExistingRfq[]>([]),[messages,setMessages]=useState<Message[]>([])
 const[templates,setTemplates]=useState<Template[]>([]),[templateId,setTemplateId]=useState(''),[templateName,setTemplateName]=useState('Standard RFQ'),[subject,setSubject]=useState('Rate request | {{request_number}} | {{route}}'),[body,setBody]=useState('Good morning,\n\nPlease provide your best rate for the shipment below.\n\nRequest number:\n{{request_number}}\n\nCustomer reference:\n{{customer_reference}}\n\nMode / service:\n{{mode}} · {{service_level}}\n\nRoute:\n{{route}}\n\nCargo:\n{{cargo_summary}}\n\nEstimated departure:\n{{estimated_departure}}\n\nSpecial instructions:\n{{special_instructions}}\n\nPlease include your complete freight and surcharge breakdown, minimum charges, routing, carrier, transit time, frequency, validity, inclusions, and exclusions.\n\nThank you,\nMIP Cargo Express')
 const[isDefault,setIsDefault]=useState(false),[editingTemplate,setEditingTemplate]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState(''),[followup,setFollowup]=useState(''),[menu,setMenu]=useState(false),[templateMenu,setTemplateMenu]=useState(false),[emailConnected,setEmailConnected]=useState<boolean|null>(null),[editorTarget,setEditorTarget]=useState<EditorTarget>('body')
 const subjectRef=useRef<HTMLInputElement>(null),bodyRef=useRef<HTMLTextAreaElement>(null)
 const active=useMemo(()=>rfqs.find(item=>item.id===rfqId)||null,[rfqs,rfqId])
 const visibleVendors=useMemo(()=>vendors.filter(v=>[v.company,v.general_email].join(' ').toLowerCase().includes(search.toLowerCase())&&(!request.mode||!v.modes?.length||v.modes.some(item=>item.toLowerCase()===request.mode?.toLowerCase()))),[vendors,search,request.mode])
 const selectedVendors=useMemo(()=>vendors.filter(v=>selected.includes(v.id)),[vendors,selected])
 const savedTemplate=templates.find(item=>item.id===templateId)
 const templateChanged=!savedTemplate||templateName!==savedTemplate.name||subject!==savedTemplate.subject_template||body!==savedTemplate.body_template||isDefault!==Boolean(savedTemplate.is_default)

 const load=async()=>{setLoading(true);const[v,r,t,status]=await Promise.all([
  supabase.from('vendors').select('id,company,preferred,modes,general_email,vendor_contacts(id,name,email,is_primary)').is('archived_at',null).order('preferred',{ascending:false}).order('company'),
  supabase.from('vendor_rfqs').select('id,rfq_number,status,sent_to,subject,message_body,sent_at,response_data,vendors(company)').eq('quote_request_id',request.id).order('created_at',{ascending:false}),
  supabase.from('rfq_templates').select('id,name,subject_template,body_template,is_default,active').eq('active',true).order('is_default',{ascending:false}).order('name'),
  getResendConnectionStatus().catch(()=>({connected:false}))
 ]);setVendors((v.data||[]) as unknown as Vendor[]);setRfqs((r.data||[]) as unknown as ExistingRfq[]);const loaded=(t.data||[]) as Template[];setTemplates(loaded);setEmailConnected(Boolean(status?.connected));const preferred=loaded.find(item=>item.is_default)||loaded[0];if(preferred){applyTemplate(preferred)}setLoading(false)}
 useEffect(()=>{void load()},[request.id])
 useEffect(()=>{if(mode!=='vendor-chat'||!rfqId){setMessages([]);return}const fetchMessages=async()=>{const{data}=await supabase.from('rfq_conversation_messages').select('id,direction,sender_email,recipient_email,subject,body_text,status,sent_at,received_at,created_at,attachments').eq('vendor_rfq_id',rfqId).order('created_at');setMessages((data||[]) as Message[])};void fetchMessages();const channel=supabase.channel(`rfq-screen-${rfqId}`).on('postgres_changes',{event:'*',schema:'public',table:'rfq_conversation_messages',filter:`vendor_rfq_id=eq.${rfqId}`},()=>void fetchMessages()).subscribe();return()=>{void supabase.removeChannel(channel)}},[mode,rfqId])

 function applyTemplate(template:Template){setTemplateId(template.id);setTemplateName(template.name);setSubject(template.subject_template);setBody(template.body_template);setIsDefault(Boolean(template.is_default));setEditingTemplate(false);setFeedback('')}
 const confirmDiscard=()=>!templateChanged||confirm('Discard your unsaved template changes?')
 const closeComposer=()=>{if(confirmDiscard())onClose()}
 const chooseTemplate=(id:string)=>{if(!confirmDiscard())return;const template=templates.find(item=>item.id===id);if(template)applyTemplate(template);else startNewTemplate()}
 const startNewTemplate=()=>{setTemplateId('');setTemplateName('New RFQ template');setSubject('Rate request | {{request_number}} | {{route}}');setBody('Good morning,\n\nPlease provide your best rate for {{route}}.\n\nRequest number: {{request_number}}\nCargo: {{cargo_summary}}\n\nThank you,\nMIP Cargo Express');setIsDefault(false);setEditingTemplate(true);setFeedback('New template draft')}
 const duplicateTemplate=()=>{setTemplateId('');setTemplateName(`${templateName} copy`);setIsDefault(false);setEditingTemplate(true);setFeedback('Template duplicated. Save it as a new template.')}
 const saveTemplate=async(asNew=false)=>{if(!templateName.trim()||!subject.trim()||!body.trim())return;setSaving(true);setFeedback('Saving template…');try{
  if(isDefault){const{error}=await supabase.from('rfq_templates').update({is_default:false}).neq('id','00000000-0000-0000-0000-000000000000');if(error)throw error}
  if(templateId&&!asNew){const{data,error}=await supabase.from('rfq_templates').update({name:templateName.trim(),subject_template:subject,body_template:body,is_default:isDefault,active:true}).eq('id',templateId).select('id,name,subject_template,body_template,is_default,active').single();if(error)throw error;const saved=data as Template;setTemplates(current=>current.map(item=>item.id===saved.id?saved:{...item,is_default:isDefault?false:item.is_default}));applyTemplate(saved)}
  else{const{data,error}=await supabase.from('rfq_templates').insert({name:templateName.trim(),subject_template:subject,body_template:body,is_default:isDefault,active:true}).select('id,name,subject_template,body_template,is_default,active').single();if(error)throw error;const saved=data as Template;setTemplates(current=>[saved,...current.map(item=>({...item,is_default:isDefault?false:item.is_default}))]);applyTemplate(saved)}
  setFeedback('Template saved')
 }catch(error){setFeedback(error instanceof Error?error.message:'Unable to save template')}finally{setSaving(false)}}
 const deleteTemplate=async()=>{if(!templateId||!confirm(`Delete template “${templateName}”?`))return;setSaving(true);const{error}=await supabase.from('rfq_templates').update({active:false,is_default:false}).eq('id',templateId);setSaving(false);if(error){setFeedback(error.message);return}const remaining=templates.filter(item=>item.id!==templateId);setTemplates(remaining);const next=remaining.find(item=>item.is_default)||remaining[0];if(next)applyTemplate(next);else startNewTemplate();setFeedback('Template deleted')}
 const insertToken=(token:string)=>{const ref=editorTarget==='subject'?subjectRef.current:bodyRef.current;const value=editorTarget==='subject'?subject:body;const start=ref?.selectionStart??value.length,end=ref?.selectionEnd??start;const next=`${value.slice(0,start)}${token}${value.slice(end)}`;if(editorTarget==='subject')setSubject(next);else setBody(next);requestAnimationFrame(()=>{ref?.focus();ref?.setSelectionRange(start+token.length,start+token.length)})}

 const create=async()=>{if(!selected.length||!subject.trim()||!body.trim()||emailConnected!==true)return;setSaving(true);setFeedback('Creating RFQ…');try{const renderedSubject=renderTemplate(subject,request),renderedBody=renderTemplate(body,request);const rows=selectedVendors.map(v=>({rfq_number:rfqNumber(),quote_request_id:request.id,vendor_id:v.id,vendor_contact_id:contact(v)?.id||null,status:'draft',sent_to:contact(v)?.email||v.general_email,subject:renderedSubject,message_body:renderedBody,response_data:{template_id:templateId||null,template_name:templateName}}));const{data,error}=await supabase.from('vendor_rfqs').insert(rows).select('id,rfq_number,status,sent_to,subject,message_body,sent_at,response_data,vendors(company)');if(error)throw error;const created=(data||[]) as unknown as ExistingRfq[];await sendRfqEmails(created.map(item=>item.id));await supabase.from('quote_requests').update({status:'vendor_rfq',last_activity_at:new Date().toISOString()}).eq('id',request.id);await supabase.from('commercial_activities').insert({quote_request_id:request.id,activity_type:'vendor_rfq_created',title:`${created.length} vendor RFQ${created.length===1?'':'s'} created`,description:`Rate requests sent to ${created.map(item=>item.vendors?.company||item.sent_to).join(', ')}.`,actor_name:'Pricing Team'});setRfqs(current=>[...created,...current]);setFeedback('RFQ sent');onCreated();if(created[0])onModeChange('vendor-chat',created[0].id)}catch(error){setFeedback(error instanceof Error?error.message:'Unable to send RFQ')}finally{setSaving(false)}}
 const sendFollowup=async()=>{if(!active||!followup.trim()||saving)return;setSaving(true);setFeedback('Sending…');const{data,error}=await supabase.functions.invoke<{error?:string}>('send-rfq-followup',{body:{vendor_rfq_id:active.id,message:followup.trim()}});setSaving(false);if(error||data?.error){setFeedback(data?.error||error?.message||'Unable to send');return}setFollowup('');setFeedback('Sent')}
 const deleteChat=async()=>{if(!active||!confirm(`Delete chat for ${active.vendors?.company||active.sent_to||'this vendor'} (${active.rfq_number})? The RFQ and saved rates will remain.`))return;const{error}=await supabase.from('rfq_conversation_messages').delete().eq('vendor_rfq_id',active.id);if(error){setFeedback(error.message);return}setMessages([]);setMenu(false);onCreated()}
 const deleteRfq=async()=>{if(!active||!confirm(`Delete RFQ ${active.rfq_number} for ${active.vendors?.company||active.sent_to||'this vendor'} and its chat? Saved rate data and messages for this RFQ will be deleted; the request and other RFQs remain.`))return;const{error}=await supabase.from('vendor_rfqs').delete().eq('id',active.id);if(error){setFeedback(error.message);return}setMenu(false);onCreated();onClose()}

 if(loading)return <div className="rfq-source-overlay"><section className="rfq-source-screen rfq-loading">Loading RFQ workspace…</section></div>
 if(mode==='vendor-chat')return <div className="rfq-source-overlay"><section className="rfq-source-screen rfq-chat-screen" aria-label="Vendor conversation">
  <header className="rfq-chat-header"><div><small>VENDOR CONVERSATION</small><h2>{active?.vendors?.company||active?.sent_to||'Conversation unavailable'}</h2><p>{active?.rfq_number||'RFQ not found'} · {active?.sent_to||'No recipient'}</p></div><div><button onClick={onClose} aria-label="Close conversation"><X/></button><button onClick={()=>setMenu(!menu)} aria-label="Conversation menu"><MoreHorizontal/></button>{menu&&<div className="rfq-source-menu"><button onClick={deleteChat}><Trash2/>Delete chat</button><button className="danger" onClick={deleteRfq}><Trash2/>Delete RFQ</button></div>}</div></header>
  {active?.response_data&&Number(active.response_data.total)>0&&<div className="rfq-rate-strip"><span>Total</span><b>{String(active.response_data.currency||'USD')} {Number(active.response_data.total).toFixed(2)}</b>{Boolean(active.response_data.carrier)&&<span>{String(active.response_data.carrier)}</span>}{Boolean(active.response_data.transit)&&<span>{String(active.response_data.transit)}</span>}</div>}
  <main className="rfq-thread">{active&&messages.length===0&&active.message_body&&<article className="rfq-bubble outbound"><small>MIP Pricing Team · {timestamp(active.sent_at)}</small><b>{active.subject}</b><p>{active.message_body}</p><StatusBadge status={active.status}/></article>}{messages.map(item=><article key={item.id} className={`rfq-bubble ${item.direction}`}><small>{item.direction==='outbound'?'MIP Pricing Team':item.sender_email||'Vendor'} · {timestamp(item.sent_at||item.received_at||item.created_at)}</small>{item.subject&&<b>{item.subject}</b>}<p>{stripQuotedHistory(item.body_text||'No message body')}</p><StatusBadge status={item.status}/></article>)}</main>
  <footer className="rfq-followup"><div className="rfq-quick-replies">{[['Validity','Please confirm the rate validity and expiration date.'],['Inclusions','Please confirm which charges are included.'],['Transit','Please confirm transit time, routing, and frequency.']].map(([label,value])=><button key={label} onClick={()=>setFollowup(value)}>{label}</button>)}</div><div><textarea aria-label="Follow-up message" value={followup} onChange={e=>setFollowup(e.target.value)} placeholder="Write a message…" rows={2}/><button onClick={sendFollowup} disabled={!active||saving||!followup.trim()} aria-label="Send follow-up"><Send/></button></div>{feedback&&<small role="status">{feedback}</small>}</footer>
 </section></div>

 return <div className="rfq-source-overlay"><section className="rfq-source-screen rfq-new-screen" aria-label="New vendor RFQ">
  <header className="rfq-context-header"><button onClick={closeComposer}><ChevronLeft/>Back to request</button><div><small>{request.request_number}</small><h2>{requestRoute(request)}</h2><p>{request.customer_company||request.contact_name||'Customer'}</p></div><button onClick={closeComposer} aria-label="Close"><X/></button></header>
  <nav className="rfq-step-nav" aria-label="New RFQ steps"><button className={mode==='new-rfq-vendors'?'active':''} onClick={()=>onModeChange('new-rfq-vendors')}>1 <span>Vendors</span></button><button className={mode==='new-rfq-template'?'active':''} onClick={()=>selected.length&&onModeChange('new-rfq-template')} disabled={!selected.length}>2 <span>Template</span></button></nav>
  {mode==='new-rfq-vendors'?<main className="rfq-vendor-screen"><header><div><small>VENDOR DIRECTORY</small><h3>Select recipients</h3><p>{selected.length} vendor{selected.length===1?'':'s'} selected</p></div><button onClick={()=>{onClose();location.hash='#/vendors'}}><Plus/>Add vendor</button></header><label className="rfq-vendor-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search vendors"/></label><div className="rfq-vendor-list">{visibleVendors.map(v=>{const email=contact(v)?.email||v.general_email;const checked=selected.includes(v.id);return <button key={v.id} className={checked?'selected':''} disabled={!email} onClick={()=>setSelected(current=>checked?current.filter(id=>id!==v.id):[...current,v.id])}><span><b>{v.company}{v.preferred&&<em><Star size={14}/>Preferred</em>}</b><small>{email||'Email required'}</small></span><span className="rfq-vendor-check">{checked&&<Check/>}</span></button>})}</div><footer><span>{selected.length} selected</span><Button onClick={()=>onModeChange('new-rfq-template')} disabled={!selected.length}>Continue to Template</Button></footer></main>:
  <main className="rfq-template-screen"><section className="rfq-selected-summary"><small>RECIPIENTS</small><div>{selectedVendors.map(v=><span key={v.id}>{v.company}<button aria-label={`Remove ${v.company}`} onClick={()=>setSelected(current=>current.filter(id=>id!==v.id))}><X size={14}/></button></span>)}</div></section>
   <section className="rfq-template-manager"><div className="rfq-template-picker"><label>Template<select value={templateId} onChange={e=>chooseTemplate(e.target.value)}><option value="">Unsaved template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.is_default?'★ ':''}{t.name}</option>)}</select></label><button onClick={()=>setEditingTemplate(true)} disabled={!templateId}><Pencil/>Edit</button><button onClick={startNewTemplate}><Plus/>New</button><button onClick={duplicateTemplate}><Copy/>Duplicate</button><div className="rfq-template-more"><button onClick={()=>setTemplateMenu(v=>!v)} aria-label="More template actions"><MoreHorizontal/>More</button>{templateMenu&&<div className="rfq-source-menu"><label>Template name<input value={templateName} onChange={e=>{setTemplateName(e.target.value);setEditingTemplate(true)}}/></label><button onClick={()=>saveTemplate(true)} disabled={saving}><Copy/>Save as new</button><button onClick={()=>{setIsDefault(true);setEditingTemplate(true);setTemplateMenu(false)}} disabled={isDefault}><Star/>Make default</button><button className="danger" onClick={deleteTemplate} disabled={!templateId||isDefault}><Trash2/>Delete template</button></div>}</div></div>
    <div className="rfq-template-meta"><span>{templateChanged?'Unsaved changes':'Up to date'}</span><button onClick={()=>saveTemplate(false)} disabled={saving||!templateChanged}><Save/>Save changes</button></div>
   </section>
   <section className="rfq-token-panel"><header><div><small>DYNAMIC FIELDS</small><p>Choose Subject or Message, then insert a field.</p></div><div><button className={editorTarget==='subject'?'active':''} onClick={()=>setEditorTarget('subject')}>Subject</button><button className={editorTarget==='body'?'active':''} onClick={()=>setEditorTarget('body')}>Message</button></div></header><div>{tokenDefinitions.map(([label,token])=><button key={token} onClick={()=>insertToken(token)}>{label}</button>)}</div></section>
   <label>Subject<input ref={subjectRef} value={subject} onFocus={()=>setEditorTarget('subject')} onChange={e=>{setSubject(e.target.value);setEditingTemplate(true)}}/></label><label>Message<textarea ref={bodyRef} value={body} onFocus={()=>setEditorTarget('body')} onChange={e=>{setBody(e.target.value);setEditingTemplate(true)}} rows={12}/></label>
   <details className="rfq-template-preview"><summary>Preview with request data</summary><div><b>{renderTemplate(subject,request)}</b><p>{renderTemplate(body,request)}</p></div></details>
   <footer><Button variant="secondary" onClick={()=>onModeChange('new-rfq-vendors')}>Back to Vendors</Button><Button onClick={create} disabled={saving||!selected.length||emailConnected!==true||!subject.trim()||!body.trim()} title={!selected.length?'Select at least one recipient':emailConnected!==true?'Email sending is unavailable':!subject.trim()?'Enter a subject':!body.trim()?'Enter a message':''}><Send/>{saving?'Sending…':`Send ${selected.length} RFQ${selected.length===1?'':'s'}`}</Button></footer>{!selected.length&&<p role="alert">Select at least one recipient before sending.</p>}{emailConnected===false&&<p role="alert">Email sending is unavailable. Configure the Resend connection.</p>}{feedback&&<p role="status">{feedback}</p>}
  </main>}
 </section></div>
}
