import { Building2, Filter, LayoutGrid, LayoutList, Mail, MapPin, Pencil, Plus, Search, Star, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { Button, EmptyState, GlassCard } from './ui'

type Vendor={id:string;company:string;vendor_type:string;general_email:string|null;phone:string|null;website:string|null;payment_terms:string|null;default_currency:string|null;modes:string[]|null;countries:string[]|null;preferred:boolean|null;notes:string|null;status:string}
type View='list'|'grid'
const vendorTypes=[['airline','Airline'],['gsa','GSA'],['air_cargo_agent','Air Cargo Agent'],['nvocc','NVOCC'],['ocean_carrier','Ocean Carrier'],['co_loader','Co-loader'],['trucker','Trucker'],['drayage_carrier','Drayage Carrier'],['customs_broker','Customs Broker'],['warehouse_cfs','Warehouse / CFS'],['courier','Courier'],['overseas_agent','Overseas Agent'],['service_provider','Other Service Provider']] as const
const label=(v:string)=>vendorTypes.find(x=>x[0]===v)?.[1]||(v||'service provider').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())

export function VendorsPage(){
 const location=useLocation(),navigate=useNavigate()
 const[vendors,setVendors]=useState<Vendor[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[type,setType]=useState(''),[preferred,setPreferred]=useState('all'),[mode,setMode]=useState(''),[country,setCountry]=useState(''),[email,setEmail]=useState('all'),[status,setStatus]=useState('active'),[filtersOpen,setFiltersOpen]=useState(false)
 const[view,setView]=useState<View>(()=>(sessionStorage.getItem('vendor-view') as View)||'grid')
 const load=()=>{setLoading(true);setError('');supabase.from('vendors').select('*').order('preferred',{ascending:false}).order('company').then(({data,error})=>{setVendors((data||[]) as Vendor[]);setError(error?.message||'');setLoading(false)})}
 useEffect(load,[])
 useEffect(()=>{sessionStorage.setItem('vendor-view',view)},[view])
 useEffect(()=>{const refresh=()=>load();window.addEventListener('vendor-directory-changed',refresh);return()=>window.removeEventListener('vendor-directory-changed',refresh)},[])
 const openEditor=(vendor:Vendor|null)=>window.dispatchEvent(new CustomEvent('open-premium-vendor-editor',{detail:vendor}))
 useEffect(()=>{const params=new URLSearchParams(location.search);if(params.get('new')==='1'){openEditor(null);navigate('/vendors',{replace:true})}},[location.search,navigate])
 const modes=useMemo(()=>[...new Set(vendors.flatMap(v=>v.modes||[]))].sort(),[vendors]),countries=useMemo(()=>[...new Set(vendors.flatMap(v=>v.countries||[]))].sort(),[vendors])
 const activeCount=[type,preferred!=='all'&&preferred,mode,country,email!=='all'&&email,status!=='active'&&status].filter(Boolean).length
 const clear=()=>{setType('');setPreferred('all');setMode('');setCountry('');setEmail('all');setStatus('active')}
 const filtered=useMemo(()=>vendors.filter(v=>{
  if(status==='active'&&v.status==='archived'||status==='inactive'&&v.status!=='archived')return false
  if(type&&v.vendor_type!==type||preferred!=='all'&&Boolean(v.preferred)!==(preferred==='yes')||mode&&!v.modes?.includes(mode)||country&&!v.countries?.includes(country)||email==='yes'&&!v.general_email||email==='no'&&v.general_email)return false
  return [v.company,v.vendor_type,v.general_email,...(v.modes||[]),...(v.countries||[])].join(' ').toLowerCase().includes(search.toLowerCase())
 }),[vendors,search,type,preferred,mode,country,email,status])
 return <div className="vendor-workspace-page"><section className="vendor-workspace-header"><div><p className="eyebrow">SUPPLIER NETWORK</p><h1>Vendors</h1><p>Manage airlines, carriers, agents, brokers, warehouses, and truckers.</p></div><Button onClick={()=>openEditor(null)}><Plus size={16}/>Add vendor</Button></section><GlassCard className="vendor-directory-card">
  <div className="vendor-toolbar"><label><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search vendors, modes or countries"/></label><div className="vendor-toolbar-actions"><button className={filtersOpen?'active':''} onClick={()=>setFiltersOpen(v=>!v)}><Filter size={17}/>Filters{activeCount>0&&<span>{activeCount}</span>}</button><div className="vendor-view-toggle" aria-label="Vendor view"><button className={view==='list'?'active':''} onClick={()=>setView('list')} aria-label="List view"><LayoutList/></button><button className={view==='grid'?'active':''} onClick={()=>setView('grid')} aria-label="Grid view"><LayoutGrid/></button></div></div></div>
  {filtersOpen&&<div className="vendor-filter-panel"><label>Vendor type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{vendorTypes.map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></label><label>Preferred<select value={preferred} onChange={e=>setPreferred(e.target.value)}><option value="all">Any</option><option value="yes">Preferred</option><option value="no">Not preferred</option></select></label><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="">All modes</option>{modes.map(x=><option key={x}>{x}</option>)}</select></label><label>Country / coverage<select value={country} onChange={e=>setCountry(e.target.value)}><option value="">All coverage</option>{countries.map(x=><option key={x}>{x}</option>)}</select></label><label>Email<select value={email} onChange={e=>setEmail(e.target.value)}><option value="all">Any</option><option value="yes">Has email</option><option value="no">Missing email</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All</option></select></label><button onClick={clear}><X size={15}/>Clear all</button></div>}
  <div className="vendor-results-meta"><b>{filtered.length} vendors</b><span>{view==='list'?'List view':'Grid view'}</span></div>
  {loading?<div className="vendor-loading">Loading vendors…</div>:error?<div className="vendor-error" role="alert"><b>Vendors could not be loaded.</b><span>{error}</span><button onClick={load}>Retry</button></div>:filtered.length?<div className={`vendor-grid vendor-view-${view}`}>{filtered.map(v=><article key={v.id} className="vendor-card"><button className="vendor-card-open" onClick={()=>openEditor(v)}><div className="vendor-card-top"><div className="vendor-logo"><Building2 size={20}/></div>{v.preferred&&<span className="preferred"><Star size={12} fill="currentColor"/>Preferred</span>}</div><div className="vendor-card-identity"><h3>{v.company}</h3><p>{label(v.vendor_type)}</p></div><div className="vendor-card-meta"><span><Mail size={13}/>{v.general_email||'No email'}</span><span><MapPin size={13}/>{(v.countries||[]).slice(0,3).join(', ')||'Coverage not set'}</span></div><div className="vendor-chip-row">{(v.modes||[]).map(x=><span key={x}>{x}</span>)}</div></button><button className="vendor-edit-button" onClick={()=>openEditor(v)}><Pencil size={14}/>Edit</button></article>)}</div>:<EmptyState icon={<Building2 size={30}/>} title="No matching vendors" copy="Clear filters or add a provider."/>}
 </GlassCard></div>
}
