import { Bell, Building2, FilePlus2, FileText, Home, Menu, Plus, Search, Ship, Users, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { supabase } from './lib/supabase'
import { Button, EmptyState, GlassCard, SectionHeading, SkeletonRows, StatusBadge } from './components/ui'
import { RequestWorkspace, type RequestSummary } from './components/RequestWorkspace'
import { VendorsPage } from './components/VendorWorkspace'
import { PublicRequestPortalV2 } from './components/PublicRequestPortalV2'
import { QuoteRoute } from './components/QuoteRoute'
import { WorkspaceErrorBoundary } from './components/WorkspaceErrorBoundary'

type RequestRow=RequestSummary
const logo='https://raw.githubusercontent.com/N10ai/mip-tools/main/Untitled%20design%20-%201.png'
const navigation=[['/','Overview',Home],['/requests','Requests',Ship],['/quotes','Quotes',FileText],['/vendors','Vendors',Building2],['/customers','Customers',Users]] as const

function RequestList({items,loading,onOpen}:{items:RequestRow[],loading:boolean,onOpen:(request:RequestRow)=>void}){if(loading)return <SkeletonRows/>;if(!items.length)return <EmptyState icon={<Ship size={28}/>} title="No requests found" copy="Requests matching this view will appear here."/>;return <div className="request-list">{items.map(item=><button className="request-row" key={item.id} onClick={()=>onOpen(item)}><div><b>{item.request_number}</b><small>{new Date(item.submitted_at).toLocaleString()}</small></div><div><b>{item.customer_company||item.contact_name||'Guest request'}</b><small>{item.contact_email}</small></div><div><span>{item.mode||'Freight'} {item.service_type||''}</span><b>{item.origin_code||item.origin_name||'—'} → {item.destination_code||item.destination_name||'—'}</b></div><div><StatusBadge status={item.archived_at?'archived':item.status}/></div></button>)}</div>}
function Dashboard({requests,loading,onOpen}:{requests:RequestRow[],loading:boolean,onOpen:(r:RequestRow)=>void}){const count=(status:string)=>requests.filter(r=>r.status===status&&!r.archived_at).length;const cards=[['New requests',count('new')],['Waiting vendors',count('vendor_rfq')],['Pricing',count('pricing')],['Accepted',count('accepted')]];return <><section className="hero"><div><p className="eyebrow">COMMERCIAL OPERATIONS</p><h1>Good morning.</h1><p>Everything that needs your attention in one premium workspace.</p></div><NavLink to="/request"><Button><Plus size={17}/>New request</Button></NavLink></section><section className="stats">{cards.map(([label,value])=><GlassCard className="stat" key={label}><span>{label}</span>{loading?<div className="mini-skeleton"/>:<strong>{value}</strong>}<small>Live pipeline</small></GlassCard>)}</section><section className="grid-two"><GlassCard><SectionHeading eyebrow="LIVE PIPELINE" title="Recent requests" action={<NavLink to="/requests">View all</NavLink>}/><RequestList items={requests.filter(r=>!r.archived_at).slice(0,6)} loading={loading} onOpen={onOpen}/></GlassCard><GlassCard className="focus"><p className="eyebrow">TODAY'S FOCUS</p><h2>Priority actions</h2><div className="focus-item"><i className="purple"/><div><b>Vendor follow-ups</b><small>Review requests waiting on carrier replies.</small></div></div><div className="focus-item"><i className="blue"/><div><b>New requests</b><small>Respond while each opportunity is fresh.</small></div></div><div className="focus-item"><i className="green"/><div><b>Ready to send</b><small>Finalize and deliver completed quotes.</small></div></div></GlassCard></section></>}
function Requests({items,loading,search,setSearch,onOpen,archived,setArchived}:{items:RequestRow[],loading:boolean,search:string,setSearch:(v:string)=>void,onOpen:(r:RequestRow)=>void,archived:boolean,setArchived:(v:boolean)=>void}){return <><section className="hero compact"><div><p className="eyebrow">COMMERCIAL INTAKE</p><h1>{archived?'Archived requests':'Quote requests'}</h1><p>{archived?'Review requests removed from the active queue.':'Review, assign, request vendor rates, and create quotes.'}</p></div><NavLink to="/request"><Button><Plus size={17}/>New request</Button></NavLink></section><GlassCard><div className="toolbar"><label><Search size={17}/><input placeholder="Search requests" value={search} onChange={e=>setSearch(e.target.value)}/></label><Button variant={archived?'primary':'secondary'} onClick={()=>setArchived(!archived)}>{archived?'Active requests':'Archived'}</Button></div><RequestList items={items} loading={loading} onOpen={onOpen}/></GlassCard></>}
function Placeholder({title,copy}:{title:string,copy:string}){return <GlassCard className="placeholder"><FileText size={30}/><h1>{title}</h1><p>{copy}</p></GlassCard>}

export default function App(){
 const location=useLocation()
 const[requests,setRequests]=useState<RequestRow[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[selected,setSelected]=useState<RequestRow|null>(null),[archived,setArchived]=useState(false),[refresh,setRefresh]=useState(0),[actionsOpen,setActionsOpen]=useState(false)
 useEffect(()=>{setLoading(true);supabase.from('quote_requests').select('*').order('submitted_at',{ascending:false}).limit(250).then(({data})=>{setRequests((data||[]) as RequestRow[]);setLoading(false)})},[refresh])
 useEffect(()=>setActionsOpen(false),[location.pathname,location.search])
 const filtered=useMemo(()=>requests.filter(r=>Boolean(r.archived_at)===archived&&[r.request_number,r.customer_company,r.contact_email,r.origin_code,r.destination_code].join(' ').toLowerCase().includes(search.toLowerCase())),[requests,search,archived])
 if(location.pathname==='/request')return <PublicRequestPortalV2/>
 const quoteParams=new URLSearchParams(location.search)
 const quoteWorkspaceOpen=location.pathname==='/quotes'&&(quoteParams.has('request')||quoteParams.has('quote'))
 if(quoteWorkspaceOpen)return <WorkspaceErrorBoundary title="The Quote Workspace could not be opened."><QuoteRoute/></WorkspaceErrorBoundary>
 const changed=()=>setRefresh(v=>v+1)
 return <div className="app-bg"><div className="orb one"/><div className="orb two"/><aside className="sidebar"><div className="brand"><img src={logo}/><div><b>MIP Pricing OS</b><span>Commercial Operations</span></div></div><nav>{navigation.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' }><Icon size={18}/><span>{label}</span></NavLink>)}</nav><footer><div className="avatar">IP</div><div><b>Pricing Team</b><span>MIP Cargo Express</span></div></footer></aside><header className="topbar"><button className="mobile-menu"><Menu size={20}/></button><button className="global-search"><Search size={17}/><span>Search requests, quotes, vendors...</span><kbd>⌘ K</kbd></button><div><button className="icon"><Bell size={18}/></button><NavLink to="/request"><Button><Plus size={17}/>New</Button></NavLink></div></header><main className="workspace"><Routes><Route path="/" element={<Dashboard requests={requests} loading={loading} onOpen={setSelected}/>}/><Route path="/requests" element={<Requests items={filtered} loading={loading} search={search} setSearch={setSearch} onOpen={setSelected} archived={archived} setArchived={setArchived}/>}/><Route path="/quotes" element={<WorkspaceErrorBoundary title="Quotes could not be loaded."><QuoteRoute/></WorkspaceErrorBoundary>}/><Route path="/vendors" element={<VendorsPage/>}/><Route path="/customers" element={<Placeholder title="Customers" copy="Customer profiles and commercial history."/>}/></Routes></main><div className={`mobile-action-sheet ${actionsOpen?'open':''}`} aria-hidden={!actionsOpen}><button className="mobile-action-backdrop" onClick={()=>setActionsOpen(false)} aria-label="Close actions"/><section><header><div><small>QUICK ACTIONS</small><h2>Create new</h2></div><button onClick={()=>setActionsOpen(false)}><X size={18}/></button></header><NavLink to="/request"><span><Ship size={20}/></span><div><b>Freight request</b><small>Start a customer pricing request</small></div></NavLink><NavLink to="/quotes"><span><FilePlus2 size={20}/></span><div><b>Quote</b><small>Create or continue a quotation</small></div></NavLink><NavLink to="/vendors"><span><Building2 size={20}/></span><div><b>Vendor</b><small>Add or manage a service provider</small></div></NavLink></section></div><nav className="bottom-nav">{navigation.slice(0,3).map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' }><Icon size={19}/><span>{label}</span></NavLink>)}<button className={`mobile-action-trigger ${actionsOpen?'open':''}`} onClick={()=>setActionsOpen(v=>!v)} aria-label="Open quick actions"><Plus size={22}/></button><NavLink to="/vendors"><Building2 size={19}/><span>Vendors</span></NavLink></nav><RequestWorkspace request={selected} onClose={()=>setSelected(null)} onChanged={changed}/></div>
}