import { Bell, Building2, FileText, Home, Menu, Plus, Search, Ship, Users } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { NavLink, Route, Routes } from 'react-router-dom'
import { supabase } from './lib/supabase'
import { Button, EmptyState, GlassCard, SectionHeading, SkeletonRows, StatusBadge } from './components/ui'
import { RequestWorkspace, type RequestSummary } from './components/RequestWorkspace'
import { VendorsPage } from './components/VendorWorkspace'

type RequestRow=RequestSummary
const logo='https://raw.githubusercontent.com/N10ai/mip-tools/main/Untitled%20design%20-%201.png'
const navigation=[['/','Overview',Home],['/requests','Requests',Ship],['/quotes','Quotes',FileText],['/vendors','Vendors',Building2],['/customers','Customers',Users]] as const

function RequestList({items,loading,onOpen}:{items:RequestRow[],loading:boolean,onOpen:(request:RequestRow)=>void}){
 if(loading)return <SkeletonRows/>
 if(!items.length)return <EmptyState icon={<Ship size={28}/>} title="No requests found" copy="New customer requests will appear here."/>
 return <div className="request-list">{items.map(item=><button className="request-row" key={item.id} onClick={()=>onOpen(item)}><div><b>{item.request_number}</b><small>{new Date(item.submitted_at).toLocaleString()}</small></div><div><b>{item.customer_company||item.contact_name||'Guest request'}</b><small>{item.contact_email}</small></div><div><span>{item.mode||'Freight'} {item.service_type||''}</span><b>{item.origin_code||item.origin_name||'—'} → {item.destination_code||item.destination_name||'—'}</b></div><div><StatusBadge status={item.status}/></div></button>)}</div>
}
function Dashboard({requests,loading,onOpen}:{requests:RequestRow[],loading:boolean,onOpen:(r:RequestRow)=>void}){const count=(status:string)=>requests.filter(r=>r.status===status).length;const cards=[['New requests',count('new')],['Waiting vendors',count('vendor_rfq')],['Pricing',count('pricing')],['Accepted',count('accepted')]];return <><section className="hero"><div><p className="eyebrow">COMMERCIAL OPERATIONS</p><h1>Good morning.</h1><p>Everything that needs your attention in one premium workspace.</p></div><Button><Plus size={17}/>New request</Button></section><section className="stats">{cards.map(([label,value])=><GlassCard className="stat" key={label}><span>{label}</span>{loading?<div className="mini-skeleton"/>:<strong>{value}</strong>}<small>Live pipeline</small></GlassCard>)}</section><section className="grid-two"><GlassCard><SectionHeading eyebrow="LIVE PIPELINE" title="Recent requests" action={<NavLink to="/requests">View all</NavLink>}/><RequestList items={requests.slice(0,6)} loading={loading} onOpen={onOpen}/></GlassCard><GlassCard className="focus"><p className="eyebrow">TODAY'S FOCUS</p><h2>Priority actions</h2><div className="focus-item"><i className="purple"/><div><b>Vendor follow-ups</b><small>Review requests waiting on carrier replies.</small></div></div><div className="focus-item"><i className="blue"/><div><b>New requests</b><small>Respond while each opportunity is fresh.</small></div></div><div className="focus-item"><i className="green"/><div><b>Ready to send</b><small>Finalize and deliver completed quotes.</small></div></div></GlassCard></section></>}
function Requests({items,loading,search,setSearch,onOpen}:{items:RequestRow[],loading:boolean,search:string,setSearch:(v:string)=>void,onOpen:(r:RequestRow)=>void}){return <><section className="hero compact"><div><p className="eyebrow">COMMERCIAL INTAKE</p><h1>Quote requests</h1><p>Review, assign, request vendor rates, and create quotes.</p></div><Button><Plus size={17}/>New request</Button></section><GlassCard><div className="toolbar"><label><Search size={17}/><input placeholder="Search requests" value={search} onChange={e=>setSearch(e.target.value)}/></label><Button variant="secondary">All statuses</Button></div><RequestList items={items} loading={loading} onOpen={onOpen}/></GlassCard></>}
function Placeholder({title,copy}:{title:string,copy:string}){return <GlassCard className="placeholder"><FileText size={30}/><h1>{title}</h1><p>{copy}</p></GlassCard>}
export default function App(){const[requests,setRequests]=useState<RequestRow[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const[selected,setSelected]=useState<RequestRow|null>(null);useEffect(()=>{supabase.from('quote_requests').select('*').is('archived_at',null).order('submitted_at',{ascending:false}).limit(100).then(({data})=>{setRequests((data||[]) as RequestRow[]);setLoading(false)})},[]);const filtered=useMemo(()=>requests.filter(r=>[r.request_number,r.customer_company,r.contact_email,r.origin_code,r.destination_code].join(' ').toLowerCase().includes(search.toLowerCase())),[requests,search]);return <div className="app-bg"><div className="orb one"/><div className="orb two"/><aside className="sidebar"><div className="brand"><img src={logo}/><div><b>MIP Pricing OS</b><span>Commercial Operations</span></div></div><nav>{navigation.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><footer><div className="avatar">IP</div><div><b>Pricing Team</b><span>MIP Cargo Express</span></div></footer></aside><header className="topbar"><button className="mobile-menu"><Menu size={20}/></button><button className="global-search"><Search size={17}/><span>Search requests, quotes, vendors...</span><kbd>⌘ K</kbd></button><div><button className="icon"><Bell size={18}/></button><Button><Plus size={17}/>New</Button></div></header><main className="workspace"><Routes><Route path="/" element={<Dashboard requests={requests} loading={loading} onOpen={setSelected}/>}/><Route path="/requests" element={<Requests items={filtered} loading={loading} search={search} setSearch={setSearch} onOpen={setSelected}/>}/><Route path="/quotes" element={<Placeholder title="Quotes" copy="The premium quote workspace is next."/>}/><Route path="/vendors" element={<VendorsPage/>}/><Route path="/customers" element={<Placeholder title="Customers" copy="Customer profiles and commercial history."/>}/></Routes></main><nav className="bottom-nav">{navigation.slice(0,4).map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'}><Icon size={19}/><span>{label}</span></NavLink>)}<button><Menu size={19}/><span>More</span></button></nav><RequestWorkspace request={selected} onClose={()=>setSelected(null)}/></div>}
