import React from 'react'
import ReactDOM from 'react-dom/client'
import { HashRouter } from 'react-router-dom'
import App from './App'
import { AppEnhancements } from './components/AppEnhancements'
import { PremiumMobileInteractions } from './components/PremiumMobileInteractions'
import { MobileAccountDrawerEnhancer } from './components/MobileAccountDrawerEnhancer'
import { MobileQueueControls } from './components/MobileQueueControls'
import { MobileRequestNavigation } from './components/MobileRequestNavigation'
import { MobileQuoteSwipeEnhancer } from './components/MobileQuoteSwipeEnhancer'
import { MobileQuotePdfEnhancer } from './components/MobileQuotePdfEnhancer'
import { DesktopQuoteFocusEnhancer } from './components/DesktopQuoteFocusEnhancer'
import { RfqQuickActions } from './components/RfqQuickActions'
import { DesktopWorkspaceQueue } from './components/DesktopWorkspaceQueue'
import { DesktopCommercialEnhancements } from './components/DesktopCommercialEnhancements'
import { AuthGate } from './components/AuthGate'
import './design-system/tokens.css'
import './design-system/components.css'
import './styles.css'
import './premium.css'
import './request-workspace.css'
import './vendor-workspace.css'
import './public-portal.css'
import './public-portal-v2.css'
import './public-portal-cargo-premium.css'
import './stability-fixes.css'
import './rfq-composer.css'
import './pricing-workspace.css'
import './rfq-template-builder.css'
import './template-field-editor.css'
import './vendor-rate-workspace.css'
import './quote-workspace.css'
import './quote-workspace-v2.css'
import './auth-gate.css'
import './quote-workspace-layout-fix.css'
import './workspace-stability.css'
import './quote-management.css'
import './quote-output-and-rate-basis.css'
import './pricing-usability-fixes.css'
import './quote-mobile-workspace.css'
import './controlled-pricing-and-print.css'
import './final-ui-stabilization.css'
import './universal-selector.css'
import './mobile-stability-final.css'
import './mobile-system-v2.css'
import './mobile-quote-app.css'
import './mobile-vendor-rate.css'
import './mobile-public-request.css'
import './premium-mobile-v3.css'
import './mobile-quote-tabs-fix.css'
import './mobile-rebuild.css'
import './mobile-native-v1.css'
import './mobile-native-v2.css'
import './mobile-native-v3.css'
import './mobile-native-v4.css'
import './mobile-overview-v1.css'
import './mobile-native-v5.css'
import './mobile-global-search.css'
import './mobile-account-v2.css'
import './mobile-account-menu-fix.css'
import './mobile-account-drawer.css'
import './mobile-account-drawer-native.css'
import './mobile-request-queue-v2.css'
import './mobile-request-queue-v3.css'
import './mobile-request-queue-compact.css'
import './mobile-request-queue-v4.css'
import './mobile-request-account-final.css'
import './mobile-quote-queue-v1.css'
import './request-decision-workspace.css'
import './mobile-rfq-composer.css'
import './rfq-mobile-exact.css'
import './rfq-mobile-interactions.css'
import './rfq-mobile-final-tuning.css'
import './rfq-quick-vendor.css'
import './mobile-vendor-response-v2.css'
import './rfq-quick-vendor-primary-fix.css'
import './rfq-rate-decision-cards.css'
import './request-rates-compact-final.css'
import './desktop-workspace-v1.css'
import './desktop-workspace-v3.css'
import './premium-workspace-v4.css'
import './desktop-rail-tooltips-v5.css'
import './desktop-layout-stability-v6.css'
import './desktop-commercial-polish-v7.css'
import './desktop-final-fixes-v8.css'
import './apple-request-workspace-v8.css'
import './quote-apple-workspace-v10.css'
import './apple-quote-workspace-v10.css'
import './mobile-quote-apple-v2.css'
import './mobile-quote-apple-v12.css'
import './professional-quote-document-v3.css'
import './mobile-quote-summary-v2.css'
import './desktop-quote-redesign-v1.css'
import './desktop-quote-redesign-v2.css'
import './desktop-quote-focus-v3.css'
import './quote-workspace-v4.css'
import './quote-workspace-v5.css'
import './quote-workspace-v6.css'
import './quote-workspace-v7.css'
import './quotes-page-v2.css'
import './quote-workspace-v8.css'
import './quote-workspace-v9.css'
import './gmail-rfq-automation.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <HashRouter>
      <AuthGate>
        <AppEnhancements />
        <PremiumMobileInteractions />
        <MobileAccountDrawerEnhancer />
        <MobileQueueControls />
        <MobileRequestNavigation />
        <MobileQuoteSwipeEnhancer />
        <MobileQuotePdfEnhancer />
        <DesktopQuoteFocusEnhancer />
        <RfqQuickActions />
        <DesktopWorkspaceQueue />
        <DesktopCommercialEnhancements />
        <App />
      </AuthGate>
    </HashRouter>
  </React.StrictMode>,
)
